/********************************************************************
* Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDict();
extern void G__cpp_setup_inheritanceDict();
extern void G__cpp_setup_typetableDict();
extern void G__cpp_setup_memvarDict();
extern void G__cpp_setup_globalDict();
extern void G__cpp_setup_memfuncDict();
extern void G__cpp_setup_funcDict();
extern void G__set_cpp_environmentDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__DictLN_vectorlEintcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
typedef vector<int,allocator<int> > G__vectorlEintcOallocatorlEintgRsPgR;
