//////////////////////////////////////////////////////////
// This class has been automatically generated on
// Fri Jun 23 09:46:54 2017 by ROOT version 5.34/26
// from TTree evetree/event tree
// found on file: RPC_evtraw-r212230.dat
//////////////////////////////////////////////////////////

//This class now contains timestamps for all the layer data and as well as event number of all the layers


#ifndef RPCEve_h
#define RPCEve_h

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

// Header file for the classes stored in the TTree if any.
#include <TTimeStamp.h>
#include <TBits.h>
#include <vector>
#define NL 12
#define NC 8

// Fixed size dimensions of array or collections stored in the TTree if any.

class RPCEve {
public :
   TTree          *fChain;   //!pointer to the analyzed TTree or TChain
   Int_t           fCurrent; //!current Tree number in a TChain

   // Declaration of leaf types
   Int_t           ENum[12];
   Int_t           REnum[12];
   ULong64_t       CEnum;
   //TTimeStamp      *Evetime;
   TTimeStamp      *Evetime_0;
   TTimeStamp      *Evetime_1;
   TTimeStamp      *Evetime_2;
   TTimeStamp      *Evetime_3;
   TTimeStamp      *Evetime_4;
   TTimeStamp      *Evetime_5;
   TTimeStamp      *Evetime_6;
   TTimeStamp      *Evetime_7;
   TTimeStamp      *Evetime_8;
   TTimeStamp      *Evetime_9;
   TTimeStamp      *Evetime_10;
   TTimeStamp      *Evetime_11;
   TBits           *xstriphitsL0;
   TBits           *ystriphitsL0;
   TBits           *xstriphitsL1;
   TBits           *ystriphitsL1;
   TBits           *xstriphitsL2;
   TBits           *ystriphitsL2;
   TBits           *xstriphitsL3;
   TBits           *ystriphitsL3;
   TBits           *xstriphitsL4;
   TBits           *ystriphitsL4;
   TBits           *xstriphitsL5;
   TBits           *ystriphitsL5;
   TBits           *xstriphitsL6;
   TBits           *ystriphitsL6;
   TBits           *xstriphitsL7;
   TBits           *ystriphitsL7;
   TBits           *xstriphitsL8;
   TBits           *ystriphitsL8;
   TBits           *xstriphitsL9;
   TBits           *ystriphitsL9;
   TBits           *xstriphitsL10;
   TBits           *ystriphitsL10;
   TBits           *xstriphitsL11;
   TBits           *ystriphitsL11;
   // ULong64_t       tdc_ref_l[12];
   // ULong64_t       tdc_ref_t[12];
   Int_t       tdc_ref_l[12];
   Int_t       tdc_ref_t[12];
   //add here for trigger difference
   Int_t           trigCntDiff[12];     //Added by esha 04/11/2017
   std::vector<unsigned int> *xtdc_l_0_0;
   std::vector<unsigned int> *ytdc_l_0_0;
   std::vector<unsigned int> *xtdc_t_0_0;
   std::vector<unsigned int> *ytdc_t_0_0;
   std::vector<unsigned int> *xtdc_l_0_1;
   std::vector<unsigned int> *ytdc_l_0_1;
   std::vector<unsigned int> *xtdc_t_0_1;
   std::vector<unsigned int> *ytdc_t_0_1;
   std::vector<unsigned int> *xtdc_l_0_2;
   std::vector<unsigned int> *ytdc_l_0_2;
   std::vector<unsigned int> *xtdc_t_0_2;
   std::vector<unsigned int> *ytdc_t_0_2;
   std::vector<unsigned int> *xtdc_l_0_3;
   std::vector<unsigned int> *ytdc_l_0_3;
   std::vector<unsigned int> *xtdc_t_0_3;
   std::vector<unsigned int> *ytdc_t_0_3;
   std::vector<unsigned int> *xtdc_l_0_4;
   std::vector<unsigned int> *ytdc_l_0_4;
   std::vector<unsigned int> *xtdc_t_0_4;
   std::vector<unsigned int> *ytdc_t_0_4;
   std::vector<unsigned int> *xtdc_l_0_5;
   std::vector<unsigned int> *ytdc_l_0_5;
   std::vector<unsigned int> *xtdc_t_0_5;
   std::vector<unsigned int> *ytdc_t_0_5;
   std::vector<unsigned int> *xtdc_l_0_6;
   std::vector<unsigned int> *ytdc_l_0_6;
   std::vector<unsigned int> *xtdc_t_0_6;
   std::vector<unsigned int> *ytdc_t_0_6;
   std::vector<unsigned int> *xtdc_l_0_7;
   std::vector<unsigned int> *ytdc_l_0_7;
   std::vector<unsigned int> *xtdc_t_0_7;
   std::vector<unsigned int> *ytdc_t_0_7;
   std::vector<unsigned int> *xtdc_l_1_0;
   std::vector<unsigned int> *ytdc_l_1_0;
   std::vector<unsigned int> *xtdc_t_1_0;
   std::vector<unsigned int> *ytdc_t_1_0;
   std::vector<unsigned int> *xtdc_l_1_1;
   std::vector<unsigned int> *ytdc_l_1_1;
   std::vector<unsigned int> *xtdc_t_1_1;
   std::vector<unsigned int> *ytdc_t_1_1;
   std::vector<unsigned int> *xtdc_l_1_2;
   std::vector<unsigned int> *ytdc_l_1_2;
   std::vector<unsigned int> *xtdc_t_1_2;
   std::vector<unsigned int> *ytdc_t_1_2;
   std::vector<unsigned int> *xtdc_l_1_3;
   std::vector<unsigned int> *ytdc_l_1_3;
   std::vector<unsigned int> *xtdc_t_1_3;
   std::vector<unsigned int> *ytdc_t_1_3;
   std::vector<unsigned int> *xtdc_l_1_4;
   std::vector<unsigned int> *ytdc_l_1_4;
   std::vector<unsigned int> *xtdc_t_1_4;
   std::vector<unsigned int> *ytdc_t_1_4;
   std::vector<unsigned int> *xtdc_l_1_5;
   std::vector<unsigned int> *ytdc_l_1_5;
   std::vector<unsigned int> *xtdc_t_1_5;
   std::vector<unsigned int> *ytdc_t_1_5;
   std::vector<unsigned int> *xtdc_l_1_6;
   std::vector<unsigned int> *ytdc_l_1_6;
   std::vector<unsigned int> *xtdc_t_1_6;
   std::vector<unsigned int> *ytdc_t_1_6;
   std::vector<unsigned int> *xtdc_l_1_7;
   std::vector<unsigned int> *ytdc_l_1_7;
   std::vector<unsigned int> *xtdc_t_1_7;
   std::vector<unsigned int> *ytdc_t_1_7;
   std::vector<unsigned int> *xtdc_l_2_0;
   std::vector<unsigned int> *ytdc_l_2_0;
   std::vector<unsigned int> *xtdc_t_2_0;
   std::vector<unsigned int> *ytdc_t_2_0;
   std::vector<unsigned int> *xtdc_l_2_1;
   std::vector<unsigned int> *ytdc_l_2_1;
   std::vector<unsigned int> *xtdc_t_2_1;
   std::vector<unsigned int> *ytdc_t_2_1;
   std::vector<unsigned int> *xtdc_l_2_2;
   std::vector<unsigned int> *ytdc_l_2_2;
   std::vector<unsigned int> *xtdc_t_2_2;
   std::vector<unsigned int> *ytdc_t_2_2;
   std::vector<unsigned int> *xtdc_l_2_3;
   std::vector<unsigned int> *ytdc_l_2_3;
   std::vector<unsigned int> *xtdc_t_2_3;
   std::vector<unsigned int> *ytdc_t_2_3;
   std::vector<unsigned int> *xtdc_l_2_4;
   std::vector<unsigned int> *ytdc_l_2_4;
   std::vector<unsigned int> *xtdc_t_2_4;
   std::vector<unsigned int> *ytdc_t_2_4;
   std::vector<unsigned int> *xtdc_l_2_5;
   std::vector<unsigned int> *ytdc_l_2_5;
   std::vector<unsigned int> *xtdc_t_2_5;
   std::vector<unsigned int> *ytdc_t_2_5;
   std::vector<unsigned int> *xtdc_l_2_6;
   std::vector<unsigned int> *ytdc_l_2_6;
   std::vector<unsigned int> *xtdc_t_2_6;
   std::vector<unsigned int> *ytdc_t_2_6;
   std::vector<unsigned int> *xtdc_l_2_7;
   std::vector<unsigned int> *ytdc_l_2_7;
   std::vector<unsigned int> *xtdc_t_2_7;
   std::vector<unsigned int> *ytdc_t_2_7;
   std::vector<unsigned int> *xtdc_l_3_0;
   std::vector<unsigned int> *ytdc_l_3_0;
   std::vector<unsigned int> *xtdc_t_3_0;
   std::vector<unsigned int> *ytdc_t_3_0;
   std::vector<unsigned int> *xtdc_l_3_1;
   std::vector<unsigned int> *ytdc_l_3_1;
   std::vector<unsigned int> *xtdc_t_3_1;
   std::vector<unsigned int> *ytdc_t_3_1;
   std::vector<unsigned int> *xtdc_l_3_2;
   std::vector<unsigned int> *ytdc_l_3_2;
   std::vector<unsigned int> *xtdc_t_3_2;
   std::vector<unsigned int> *ytdc_t_3_2;
   std::vector<unsigned int> *xtdc_l_3_3;
   std::vector<unsigned int> *ytdc_l_3_3;
   std::vector<unsigned int> *xtdc_t_3_3;
   std::vector<unsigned int> *ytdc_t_3_3;
   std::vector<unsigned int> *xtdc_l_3_4;
   std::vector<unsigned int> *ytdc_l_3_4;
   std::vector<unsigned int> *xtdc_t_3_4;
   std::vector<unsigned int> *ytdc_t_3_4;
   std::vector<unsigned int> *xtdc_l_3_5;
   std::vector<unsigned int> *ytdc_l_3_5;
   std::vector<unsigned int> *xtdc_t_3_5;
   std::vector<unsigned int> *ytdc_t_3_5;
   std::vector<unsigned int> *xtdc_l_3_6;
   std::vector<unsigned int> *ytdc_l_3_6;
   std::vector<unsigned int> *xtdc_t_3_6;
   std::vector<unsigned int> *ytdc_t_3_6;
   std::vector<unsigned int> *xtdc_l_3_7;
   std::vector<unsigned int> *ytdc_l_3_7;
   std::vector<unsigned int> *xtdc_t_3_7;
   std::vector<unsigned int> *ytdc_t_3_7;
   std::vector<unsigned int> *xtdc_l_4_0;
   std::vector<unsigned int> *ytdc_l_4_0;
   std::vector<unsigned int> *xtdc_t_4_0;
   std::vector<unsigned int> *ytdc_t_4_0;
   std::vector<unsigned int> *xtdc_l_4_1;
   std::vector<unsigned int> *ytdc_l_4_1;
   std::vector<unsigned int> *xtdc_t_4_1;
   std::vector<unsigned int> *ytdc_t_4_1;
   std::vector<unsigned int> *xtdc_l_4_2;
   std::vector<unsigned int> *ytdc_l_4_2;
   std::vector<unsigned int> *xtdc_t_4_2;
   std::vector<unsigned int> *ytdc_t_4_2;
   std::vector<unsigned int> *xtdc_l_4_3;
   std::vector<unsigned int> *ytdc_l_4_3;
   std::vector<unsigned int> *xtdc_t_4_3;
   std::vector<unsigned int> *ytdc_t_4_3;
   std::vector<unsigned int> *xtdc_l_4_4;
   std::vector<unsigned int> *ytdc_l_4_4;
   std::vector<unsigned int> *xtdc_t_4_4;
   std::vector<unsigned int> *ytdc_t_4_4;
   std::vector<unsigned int> *xtdc_l_4_5;
   std::vector<unsigned int> *ytdc_l_4_5;
   std::vector<unsigned int> *xtdc_t_4_5;
   std::vector<unsigned int> *ytdc_t_4_5;
   std::vector<unsigned int> *xtdc_l_4_6;
   std::vector<unsigned int> *ytdc_l_4_6;
   std::vector<unsigned int> *xtdc_t_4_6;
   std::vector<unsigned int> *ytdc_t_4_6;
   std::vector<unsigned int> *xtdc_l_4_7;
   std::vector<unsigned int> *ytdc_l_4_7;
   std::vector<unsigned int> *xtdc_t_4_7;
   std::vector<unsigned int> *ytdc_t_4_7;
   std::vector<unsigned int> *xtdc_l_5_0;
   std::vector<unsigned int> *ytdc_l_5_0;
   std::vector<unsigned int> *xtdc_t_5_0;
   std::vector<unsigned int> *ytdc_t_5_0;
   std::vector<unsigned int> *xtdc_l_5_1;
   std::vector<unsigned int> *ytdc_l_5_1;
   std::vector<unsigned int> *xtdc_t_5_1;
   std::vector<unsigned int> *ytdc_t_5_1;
   std::vector<unsigned int> *xtdc_l_5_2;
   std::vector<unsigned int> *ytdc_l_5_2;
   std::vector<unsigned int> *xtdc_t_5_2;
   std::vector<unsigned int> *ytdc_t_5_2;
   std::vector<unsigned int> *xtdc_l_5_3;
   std::vector<unsigned int> *ytdc_l_5_3;
   std::vector<unsigned int> *xtdc_t_5_3;
   std::vector<unsigned int> *ytdc_t_5_3;
   std::vector<unsigned int> *xtdc_l_5_4;
   std::vector<unsigned int> *ytdc_l_5_4;
   std::vector<unsigned int> *xtdc_t_5_4;
   std::vector<unsigned int> *ytdc_t_5_4;
   std::vector<unsigned int> *xtdc_l_5_5;
   std::vector<unsigned int> *ytdc_l_5_5;
   std::vector<unsigned int> *xtdc_t_5_5;
   std::vector<unsigned int> *ytdc_t_5_5;
   std::vector<unsigned int> *xtdc_l_5_6;
   std::vector<unsigned int> *ytdc_l_5_6;
   std::vector<unsigned int> *xtdc_t_5_6;
   std::vector<unsigned int> *ytdc_t_5_6;
   std::vector<unsigned int> *xtdc_l_5_7;
   std::vector<unsigned int> *ytdc_l_5_7;
   std::vector<unsigned int> *xtdc_t_5_7;
   std::vector<unsigned int> *ytdc_t_5_7;
   std::vector<unsigned int> *xtdc_l_6_0;
   std::vector<unsigned int> *ytdc_l_6_0;
   std::vector<unsigned int> *xtdc_t_6_0;
   std::vector<unsigned int> *ytdc_t_6_0;
   std::vector<unsigned int> *xtdc_l_6_1;
   std::vector<unsigned int> *ytdc_l_6_1;
   std::vector<unsigned int> *xtdc_t_6_1;
   std::vector<unsigned int> *ytdc_t_6_1;
   std::vector<unsigned int> *xtdc_l_6_2;
   std::vector<unsigned int> *ytdc_l_6_2;
   std::vector<unsigned int> *xtdc_t_6_2;
   std::vector<unsigned int> *ytdc_t_6_2;
   std::vector<unsigned int> *xtdc_l_6_3;
   std::vector<unsigned int> *ytdc_l_6_3;
   std::vector<unsigned int> *xtdc_t_6_3;
   std::vector<unsigned int> *ytdc_t_6_3;
   std::vector<unsigned int> *xtdc_l_6_4;
   std::vector<unsigned int> *ytdc_l_6_4;
   std::vector<unsigned int> *xtdc_t_6_4;
   std::vector<unsigned int> *ytdc_t_6_4;
   std::vector<unsigned int> *xtdc_l_6_5;
   std::vector<unsigned int> *ytdc_l_6_5;
   std::vector<unsigned int> *xtdc_t_6_5;
   std::vector<unsigned int> *ytdc_t_6_5;
   std::vector<unsigned int> *xtdc_l_6_6;
   std::vector<unsigned int> *ytdc_l_6_6;
   std::vector<unsigned int> *xtdc_t_6_6;
   std::vector<unsigned int> *ytdc_t_6_6;
   std::vector<unsigned int> *xtdc_l_6_7;
   std::vector<unsigned int> *ytdc_l_6_7;
   std::vector<unsigned int> *xtdc_t_6_7;
   std::vector<unsigned int> *ytdc_t_6_7;
   std::vector<unsigned int> *xtdc_l_7_0;
   std::vector<unsigned int> *ytdc_l_7_0;
   std::vector<unsigned int> *xtdc_t_7_0;
   std::vector<unsigned int> *ytdc_t_7_0;
   std::vector<unsigned int> *xtdc_l_7_1;
   std::vector<unsigned int> *ytdc_l_7_1;
   std::vector<unsigned int> *xtdc_t_7_1;
   std::vector<unsigned int> *ytdc_t_7_1;
   std::vector<unsigned int> *xtdc_l_7_2;
   std::vector<unsigned int> *ytdc_l_7_2;
   std::vector<unsigned int> *xtdc_t_7_2;
   std::vector<unsigned int> *ytdc_t_7_2;
   std::vector<unsigned int> *xtdc_l_7_3;
   std::vector<unsigned int> *ytdc_l_7_3;
   std::vector<unsigned int> *xtdc_t_7_3;
   std::vector<unsigned int> *ytdc_t_7_3;
   std::vector<unsigned int> *xtdc_l_7_4;
   std::vector<unsigned int> *ytdc_l_7_4;
   std::vector<unsigned int> *xtdc_t_7_4;
   std::vector<unsigned int> *ytdc_t_7_4;
   std::vector<unsigned int> *xtdc_l_7_5;
   std::vector<unsigned int> *ytdc_l_7_5;
   std::vector<unsigned int> *xtdc_t_7_5;
   std::vector<unsigned int> *ytdc_t_7_5;
   std::vector<unsigned int> *xtdc_l_7_6;
   std::vector<unsigned int> *ytdc_l_7_6;
   std::vector<unsigned int> *xtdc_t_7_6;
   std::vector<unsigned int> *ytdc_t_7_6;
   std::vector<unsigned int> *xtdc_l_7_7;
   std::vector<unsigned int> *ytdc_l_7_7;
   std::vector<unsigned int> *xtdc_t_7_7;
   std::vector<unsigned int> *ytdc_t_7_7;
   std::vector<unsigned int> *xtdc_l_8_0;
   std::vector<unsigned int> *ytdc_l_8_0;
   std::vector<unsigned int> *xtdc_t_8_0;
   std::vector<unsigned int> *ytdc_t_8_0;
   std::vector<unsigned int> *xtdc_l_8_1;
   std::vector<unsigned int> *ytdc_l_8_1;
   std::vector<unsigned int> *xtdc_t_8_1;
   std::vector<unsigned int> *ytdc_t_8_1;
   std::vector<unsigned int> *xtdc_l_8_2;
   std::vector<unsigned int> *ytdc_l_8_2;
   std::vector<unsigned int> *xtdc_t_8_2;
   std::vector<unsigned int> *ytdc_t_8_2;
   std::vector<unsigned int> *xtdc_l_8_3;
   std::vector<unsigned int> *ytdc_l_8_3;
   std::vector<unsigned int> *xtdc_t_8_3;
   std::vector<unsigned int> *ytdc_t_8_3;
   std::vector<unsigned int> *xtdc_l_8_4;
   std::vector<unsigned int> *ytdc_l_8_4;
   std::vector<unsigned int> *xtdc_t_8_4;
   std::vector<unsigned int> *ytdc_t_8_4;
   std::vector<unsigned int> *xtdc_l_8_5;
   std::vector<unsigned int> *ytdc_l_8_5;
   std::vector<unsigned int> *xtdc_t_8_5;
   std::vector<unsigned int> *ytdc_t_8_5;
   std::vector<unsigned int> *xtdc_l_8_6;
   std::vector<unsigned int> *ytdc_l_8_6;
   std::vector<unsigned int> *xtdc_t_8_6;
   std::vector<unsigned int> *ytdc_t_8_6;
   std::vector<unsigned int> *xtdc_l_8_7;
   std::vector<unsigned int> *ytdc_l_8_7;
   std::vector<unsigned int> *xtdc_t_8_7;
   std::vector<unsigned int> *ytdc_t_8_7;
   std::vector<unsigned int> *xtdc_l_9_0;
   std::vector<unsigned int> *ytdc_l_9_0;
   std::vector<unsigned int> *xtdc_t_9_0;
   std::vector<unsigned int> *ytdc_t_9_0;
   std::vector<unsigned int> *xtdc_l_9_1;
   std::vector<unsigned int> *ytdc_l_9_1;
   std::vector<unsigned int> *xtdc_t_9_1;
   std::vector<unsigned int> *ytdc_t_9_1;
   std::vector<unsigned int> *xtdc_l_9_2;
   std::vector<unsigned int> *ytdc_l_9_2;
   std::vector<unsigned int> *xtdc_t_9_2;
   std::vector<unsigned int> *ytdc_t_9_2;
   std::vector<unsigned int> *xtdc_l_9_3;
   std::vector<unsigned int> *ytdc_l_9_3;
   std::vector<unsigned int> *xtdc_t_9_3;
   std::vector<unsigned int> *ytdc_t_9_3;
   std::vector<unsigned int> *xtdc_l_9_4;
   std::vector<unsigned int> *ytdc_l_9_4;
   std::vector<unsigned int> *xtdc_t_9_4;
   std::vector<unsigned int> *ytdc_t_9_4;
   std::vector<unsigned int> *xtdc_l_9_5;
   std::vector<unsigned int> *ytdc_l_9_5;
   std::vector<unsigned int> *xtdc_t_9_5;
   std::vector<unsigned int> *ytdc_t_9_5;
   std::vector<unsigned int> *xtdc_l_9_6;
   std::vector<unsigned int> *ytdc_l_9_6;
   std::vector<unsigned int> *xtdc_t_9_6;
   std::vector<unsigned int> *ytdc_t_9_6;
   std::vector<unsigned int> *xtdc_l_9_7;
   std::vector<unsigned int> *ytdc_l_9_7;
   std::vector<unsigned int> *xtdc_t_9_7;
   std::vector<unsigned int> *ytdc_t_9_7;
   std::vector<unsigned int> *xtdc_l_10_0;
   std::vector<unsigned int> *ytdc_l_10_0;
   std::vector<unsigned int> *xtdc_t_10_0;
   std::vector<unsigned int> *ytdc_t_10_0;
   std::vector<unsigned int> *xtdc_l_10_1;
   std::vector<unsigned int> *ytdc_l_10_1;
   std::vector<unsigned int> *xtdc_t_10_1;
   std::vector<unsigned int> *ytdc_t_10_1;
   std::vector<unsigned int> *xtdc_l_10_2;
   std::vector<unsigned int> *ytdc_l_10_2;
   std::vector<unsigned int> *xtdc_t_10_2;
   std::vector<unsigned int> *ytdc_t_10_2;
   std::vector<unsigned int> *xtdc_l_10_3;
   std::vector<unsigned int> *ytdc_l_10_3;
   std::vector<unsigned int> *xtdc_t_10_3;
   std::vector<unsigned int> *ytdc_t_10_3;
   std::vector<unsigned int> *xtdc_l_10_4;
   std::vector<unsigned int> *ytdc_l_10_4;
   std::vector<unsigned int> *xtdc_t_10_4;
   std::vector<unsigned int> *ytdc_t_10_4;
   std::vector<unsigned int> *xtdc_l_10_5;
   std::vector<unsigned int> *ytdc_l_10_5;
   std::vector<unsigned int> *xtdc_t_10_5;
   std::vector<unsigned int> *ytdc_t_10_5;
   std::vector<unsigned int> *xtdc_l_10_6;
   std::vector<unsigned int> *ytdc_l_10_6;
   std::vector<unsigned int> *xtdc_t_10_6;
   std::vector<unsigned int> *ytdc_t_10_6;
   std::vector<unsigned int> *xtdc_l_10_7;
   std::vector<unsigned int> *ytdc_l_10_7;
   std::vector<unsigned int> *xtdc_t_10_7;
   std::vector<unsigned int> *ytdc_t_10_7;
   std::vector<unsigned int> *xtdc_l_11_0;
   std::vector<unsigned int> *ytdc_l_11_0;
   std::vector<unsigned int> *xtdc_t_11_0;
   std::vector<unsigned int> *ytdc_t_11_0;
   std::vector<unsigned int> *xtdc_l_11_1;
   std::vector<unsigned int> *ytdc_l_11_1;
   std::vector<unsigned int> *xtdc_t_11_1;
   std::vector<unsigned int> *ytdc_t_11_1;
   std::vector<unsigned int> *xtdc_l_11_2;
   std::vector<unsigned int> *ytdc_l_11_2;
   std::vector<unsigned int> *xtdc_t_11_2;
   std::vector<unsigned int> *ytdc_t_11_2;
   std::vector<unsigned int> *xtdc_l_11_3;
   std::vector<unsigned int> *ytdc_l_11_3;
   std::vector<unsigned int> *xtdc_t_11_3;
   std::vector<unsigned int> *ytdc_t_11_3;
   std::vector<unsigned int> *xtdc_l_11_4;
   std::vector<unsigned int> *ytdc_l_11_4;
   std::vector<unsigned int> *xtdc_t_11_4;
   std::vector<unsigned int> *ytdc_t_11_4;
   std::vector<unsigned int> *xtdc_l_11_5;
   std::vector<unsigned int> *ytdc_l_11_5;
   std::vector<unsigned int> *xtdc_t_11_5;
   std::vector<unsigned int> *ytdc_t_11_5;
   std::vector<unsigned int> *xtdc_l_11_6;
   std::vector<unsigned int> *ytdc_l_11_6;
   std::vector<unsigned int> *xtdc_t_11_6;
   std::vector<unsigned int> *ytdc_t_11_6;
   std::vector<unsigned int> *xtdc_l_11_7;
   std::vector<unsigned int> *ytdc_l_11_7;
   std::vector<unsigned int> *xtdc_t_11_7;
   std::vector<unsigned int> *ytdc_t_11_7;

   // List of branches
   TBranch        *b_ENum;   //!
   TBranch        *b_REnum;   //!
   TBranch        *b_CEnum;   //!
   //TBranch        *b_Evetime;   //!

   TBranch        *b_Evetime_0;   //!
   TBranch        *b_Evetime_1;   //!
   TBranch        *b_Evetime_2;   //!
   TBranch        *b_Evetime_3;   //!
   TBranch        *b_Evetime_4;   //!
   TBranch        *b_Evetime_5;   //!
   TBranch        *b_Evetime_6;   //!
   TBranch        *b_Evetime_7;   //!
   TBranch        *b_Evetime_8;   //!
   TBranch        *b_Evetime_9;   //!
   TBranch        *b_Evetime_10;   //!
   TBranch        *b_Evetime_11;   //!

   TBranch        *b_xstriphitsL0;   //!
   TBranch        *b_ystriphitsL0;   //!
   TBranch        *b_xstriphitsL1;   //!
   TBranch        *b_ystriphitsL1;   //!
   TBranch        *b_xstriphitsL2;   //!
   TBranch        *b_ystriphitsL2;   //!
   TBranch        *b_xstriphitsL3;   //!
   TBranch        *b_ystriphitsL3;   //!
   TBranch        *b_xstriphitsL4;   //!
   TBranch        *b_ystriphitsL4;   //!
   TBranch        *b_xstriphitsL5;   //!
   TBranch        *b_ystriphitsL5;   //!
   TBranch        *b_xstriphitsL6;   //!
   TBranch        *b_ystriphitsL6;   //!
   TBranch        *b_xstriphitsL7;   //!
   TBranch        *b_ystriphitsL7;   //!
   TBranch        *b_xstriphitsL8;   //!
   TBranch        *b_ystriphitsL8;   //!
   TBranch        *b_xstriphitsL9;   //!
   TBranch        *b_ystriphitsL9;   //!
   TBranch        *b_xstriphitsL10;   //!
   TBranch        *b_ystriphitsL10;   //!
   TBranch        *b_xstriphitsL11;   //!
   TBranch        *b_ystriphitsL11;   //!
   TBranch        *b_tdc_ref_l;   //!
   TBranch        *b_tdc_ref_t;   //!
   //add here for trigger count difference
   TBranch        *b_trigCntDiff;   //!
   TBranch        *b_xtdc_l_0_0;   //!
   TBranch        *b_ytdc_l_0_0;   //!
   TBranch        *b_xtdc_t_0_0;   //!
   TBranch        *b_ytdc_t_0_0;   //!
   TBranch        *b_xtdc_l_0_1;   //!
   TBranch        *b_ytdc_l_0_1;   //!
   TBranch        *b_xtdc_t_0_1;   //!
   TBranch        *b_ytdc_t_0_1;   //!
   TBranch        *b_xtdc_l_0_2;   //!
   TBranch        *b_ytdc_l_0_2;   //!
   TBranch        *b_xtdc_t_0_2;   //!
   TBranch        *b_ytdc_t_0_2;   //!
   TBranch        *b_xtdc_l_0_3;   //!
   TBranch        *b_ytdc_l_0_3;   //!
   TBranch        *b_xtdc_t_0_3;   //!
   TBranch        *b_ytdc_t_0_3;   //!
   TBranch        *b_xtdc_l_0_4;   //!
   TBranch        *b_ytdc_l_0_4;   //!
   TBranch        *b_xtdc_t_0_4;   //!
   TBranch        *b_ytdc_t_0_4;   //!
   TBranch        *b_xtdc_l_0_5;   //!
   TBranch        *b_ytdc_l_0_5;   //!
   TBranch        *b_xtdc_t_0_5;   //!
   TBranch        *b_ytdc_t_0_5;   //!
   TBranch        *b_xtdc_l_0_6;   //!
   TBranch        *b_ytdc_l_0_6;   //!
   TBranch        *b_xtdc_t_0_6;   //!
   TBranch        *b_ytdc_t_0_6;   //!
   TBranch        *b_xtdc_l_0_7;   //!
   TBranch        *b_ytdc_l_0_7;   //!
   TBranch        *b_xtdc_t_0_7;   //!
   TBranch        *b_ytdc_t_0_7;   //!
   TBranch        *b_xtdc_l_1_0;   //!
   TBranch        *b_ytdc_l_1_0;   //!
   TBranch        *b_xtdc_t_1_0;   //!
   TBranch        *b_ytdc_t_1_0;   //!
   TBranch        *b_xtdc_l_1_1;   //!
   TBranch        *b_ytdc_l_1_1;   //!
   TBranch        *b_xtdc_t_1_1;   //!
   TBranch        *b_ytdc_t_1_1;   //!
   TBranch        *b_xtdc_l_1_2;   //!
   TBranch        *b_ytdc_l_1_2;   //!
   TBranch        *b_xtdc_t_1_2;   //!
   TBranch        *b_ytdc_t_1_2;   //!
   TBranch        *b_xtdc_l_1_3;   //!
   TBranch        *b_ytdc_l_1_3;   //!
   TBranch        *b_xtdc_t_1_3;   //!
   TBranch        *b_ytdc_t_1_3;   //!
   TBranch        *b_xtdc_l_1_4;   //!
   TBranch        *b_ytdc_l_1_4;   //!
   TBranch        *b_xtdc_t_1_4;   //!
   TBranch        *b_ytdc_t_1_4;   //!
   TBranch        *b_xtdc_l_1_5;   //!
   TBranch        *b_ytdc_l_1_5;   //!
   TBranch        *b_xtdc_t_1_5;   //!
   TBranch        *b_ytdc_t_1_5;   //!
   TBranch        *b_xtdc_l_1_6;   //!
   TBranch        *b_ytdc_l_1_6;   //!
   TBranch        *b_xtdc_t_1_6;   //!
   TBranch        *b_ytdc_t_1_6;   //!
   TBranch        *b_xtdc_l_1_7;   //!
   TBranch        *b_ytdc_l_1_7;   //!
   TBranch        *b_xtdc_t_1_7;   //!
   TBranch        *b_ytdc_t_1_7;   //!
   TBranch        *b_xtdc_l_2_0;   //!
   TBranch        *b_ytdc_l_2_0;   //!
   TBranch        *b_xtdc_t_2_0;   //!
   TBranch        *b_ytdc_t_2_0;   //!
   TBranch        *b_xtdc_l_2_1;   //!
   TBranch        *b_ytdc_l_2_1;   //!
   TBranch        *b_xtdc_t_2_1;   //!
   TBranch        *b_ytdc_t_2_1;   //!
   TBranch        *b_xtdc_l_2_2;   //!
   TBranch        *b_ytdc_l_2_2;   //!
   TBranch        *b_xtdc_t_2_2;   //!
   TBranch        *b_ytdc_t_2_2;   //!
   TBranch        *b_xtdc_l_2_3;   //!
   TBranch        *b_ytdc_l_2_3;   //!
   TBranch        *b_xtdc_t_2_3;   //!
   TBranch        *b_ytdc_t_2_3;   //!
   TBranch        *b_xtdc_l_2_4;   //!
   TBranch        *b_ytdc_l_2_4;   //!
   TBranch        *b_xtdc_t_2_4;   //!
   TBranch        *b_ytdc_t_2_4;   //!
   TBranch        *b_xtdc_l_2_5;   //!
   TBranch        *b_ytdc_l_2_5;   //!
   TBranch        *b_xtdc_t_2_5;   //!
   TBranch        *b_ytdc_t_2_5;   //!
   TBranch        *b_xtdc_l_2_6;   //!
   TBranch        *b_ytdc_l_2_6;   //!
   TBranch        *b_xtdc_t_2_6;   //!
   TBranch        *b_ytdc_t_2_6;   //!
   TBranch        *b_xtdc_l_2_7;   //!
   TBranch        *b_ytdc_l_2_7;   //!
   TBranch        *b_xtdc_t_2_7;   //!
   TBranch        *b_ytdc_t_2_7;   //!
   TBranch        *b_xtdc_l_3_0;   //!
   TBranch        *b_ytdc_l_3_0;   //!
   TBranch        *b_xtdc_t_3_0;   //!
   TBranch        *b_ytdc_t_3_0;   //!
   TBranch        *b_xtdc_l_3_1;   //!
   TBranch        *b_ytdc_l_3_1;   //!
   TBranch        *b_xtdc_t_3_1;   //!
   TBranch        *b_ytdc_t_3_1;   //!
   TBranch        *b_xtdc_l_3_2;   //!
   TBranch        *b_ytdc_l_3_2;   //!
   TBranch        *b_xtdc_t_3_2;   //!
   TBranch        *b_ytdc_t_3_2;   //!
   TBranch        *b_xtdc_l_3_3;   //!
   TBranch        *b_ytdc_l_3_3;   //!
   TBranch        *b_xtdc_t_3_3;   //!
   TBranch        *b_ytdc_t_3_3;   //!
   TBranch        *b_xtdc_l_3_4;   //!
   TBranch        *b_ytdc_l_3_4;   //!
   TBranch        *b_xtdc_t_3_4;   //!
   TBranch        *b_ytdc_t_3_4;   //!
   TBranch        *b_xtdc_l_3_5;   //!
   TBranch        *b_ytdc_l_3_5;   //!
   TBranch        *b_xtdc_t_3_5;   //!
   TBranch        *b_ytdc_t_3_5;   //!
   TBranch        *b_xtdc_l_3_6;   //!
   TBranch        *b_ytdc_l_3_6;   //!
   TBranch        *b_xtdc_t_3_6;   //!
   TBranch        *b_ytdc_t_3_6;   //!
   TBranch        *b_xtdc_l_3_7;   //!
   TBranch        *b_ytdc_l_3_7;   //!
   TBranch        *b_xtdc_t_3_7;   //!
   TBranch        *b_ytdc_t_3_7;   //!
   TBranch        *b_xtdc_l_4_0;   //!
   TBranch        *b_ytdc_l_4_0;   //!
   TBranch        *b_xtdc_t_4_0;   //!
   TBranch        *b_ytdc_t_4_0;   //!
   TBranch        *b_xtdc_l_4_1;   //!
   TBranch        *b_ytdc_l_4_1;   //!
   TBranch        *b_xtdc_t_4_1;   //!
   TBranch        *b_ytdc_t_4_1;   //!
   TBranch        *b_xtdc_l_4_2;   //!
   TBranch        *b_ytdc_l_4_2;   //!
   TBranch        *b_xtdc_t_4_2;   //!
   TBranch        *b_ytdc_t_4_2;   //!
   TBranch        *b_xtdc_l_4_3;   //!
   TBranch        *b_ytdc_l_4_3;   //!
   TBranch        *b_xtdc_t_4_3;   //!
   TBranch        *b_ytdc_t_4_3;   //!
   TBranch        *b_xtdc_l_4_4;   //!
   TBranch        *b_ytdc_l_4_4;   //!
   TBranch        *b_xtdc_t_4_4;   //!
   TBranch        *b_ytdc_t_4_4;   //!
   TBranch        *b_xtdc_l_4_5;   //!
   TBranch        *b_ytdc_l_4_5;   //!
   TBranch        *b_xtdc_t_4_5;   //!
   TBranch        *b_ytdc_t_4_5;   //!
   TBranch        *b_xtdc_l_4_6;   //!
   TBranch        *b_ytdc_l_4_6;   //!
   TBranch        *b_xtdc_t_4_6;   //!
   TBranch        *b_ytdc_t_4_6;   //!
   TBranch        *b_xtdc_l_4_7;   //!
   TBranch        *b_ytdc_l_4_7;   //!
   TBranch        *b_xtdc_t_4_7;   //!
   TBranch        *b_ytdc_t_4_7;   //!
   TBranch        *b_xtdc_l_5_0;   //!
   TBranch        *b_ytdc_l_5_0;   //!
   TBranch        *b_xtdc_t_5_0;   //!
   TBranch        *b_ytdc_t_5_0;   //!
   TBranch        *b_xtdc_l_5_1;   //!
   TBranch        *b_ytdc_l_5_1;   //!
   TBranch        *b_xtdc_t_5_1;   //!
   TBranch        *b_ytdc_t_5_1;   //!
   TBranch        *b_xtdc_l_5_2;   //!
   TBranch        *b_ytdc_l_5_2;   //!
   TBranch        *b_xtdc_t_5_2;   //!
   TBranch        *b_ytdc_t_5_2;   //!
   TBranch        *b_xtdc_l_5_3;   //!
   TBranch        *b_ytdc_l_5_3;   //!
   TBranch        *b_xtdc_t_5_3;   //!
   TBranch        *b_ytdc_t_5_3;   //!
   TBranch        *b_xtdc_l_5_4;   //!
   TBranch        *b_ytdc_l_5_4;   //!
   TBranch        *b_xtdc_t_5_4;   //!
   TBranch        *b_ytdc_t_5_4;   //!
   TBranch        *b_xtdc_l_5_5;   //!
   TBranch        *b_ytdc_l_5_5;   //!
   TBranch        *b_xtdc_t_5_5;   //!
   TBranch        *b_ytdc_t_5_5;   //!
   TBranch        *b_xtdc_l_5_6;   //!
   TBranch        *b_ytdc_l_5_6;   //!
   TBranch        *b_xtdc_t_5_6;   //!
   TBranch        *b_ytdc_t_5_6;   //!
   TBranch        *b_xtdc_l_5_7;   //!
   TBranch        *b_ytdc_l_5_7;   //!
   TBranch        *b_xtdc_t_5_7;   //!
   TBranch        *b_ytdc_t_5_7;   //!
   TBranch        *b_xtdc_l_6_0;   //!
   TBranch        *b_ytdc_l_6_0;   //!
   TBranch        *b_xtdc_t_6_0;   //!
   TBranch        *b_ytdc_t_6_0;   //!
   TBranch        *b_xtdc_l_6_1;   //!
   TBranch        *b_ytdc_l_6_1;   //!
   TBranch        *b_xtdc_t_6_1;   //!
   TBranch        *b_ytdc_t_6_1;   //!
   TBranch        *b_xtdc_l_6_2;   //!
   TBranch        *b_ytdc_l_6_2;   //!
   TBranch        *b_xtdc_t_6_2;   //!
   TBranch        *b_ytdc_t_6_2;   //!
   TBranch        *b_xtdc_l_6_3;   //!
   TBranch        *b_ytdc_l_6_3;   //!
   TBranch        *b_xtdc_t_6_3;   //!
   TBranch        *b_ytdc_t_6_3;   //!
   TBranch        *b_xtdc_l_6_4;   //!
   TBranch        *b_ytdc_l_6_4;   //!
   TBranch        *b_xtdc_t_6_4;   //!
   TBranch        *b_ytdc_t_6_4;   //!
   TBranch        *b_xtdc_l_6_5;   //!
   TBranch        *b_ytdc_l_6_5;   //!
   TBranch        *b_xtdc_t_6_5;   //!
   TBranch        *b_ytdc_t_6_5;   //!
   TBranch        *b_xtdc_l_6_6;   //!
   TBranch        *b_ytdc_l_6_6;   //!
   TBranch        *b_xtdc_t_6_6;   //!
   TBranch        *b_ytdc_t_6_6;   //!
   TBranch        *b_xtdc_l_6_7;   //!
   TBranch        *b_ytdc_l_6_7;   //!
   TBranch        *b_xtdc_t_6_7;   //!
   TBranch        *b_ytdc_t_6_7;   //!
   TBranch        *b_xtdc_l_7_0;   //!
   TBranch        *b_ytdc_l_7_0;   //!
   TBranch        *b_xtdc_t_7_0;   //!
   TBranch        *b_ytdc_t_7_0;   //!
   TBranch        *b_xtdc_l_7_1;   //!
   TBranch        *b_ytdc_l_7_1;   //!
   TBranch        *b_xtdc_t_7_1;   //!
   TBranch        *b_ytdc_t_7_1;   //!
   TBranch        *b_xtdc_l_7_2;   //!
   TBranch        *b_ytdc_l_7_2;   //!
   TBranch        *b_xtdc_t_7_2;   //!
   TBranch        *b_ytdc_t_7_2;   //!
   TBranch        *b_xtdc_l_7_3;   //!
   TBranch        *b_ytdc_l_7_3;   //!
   TBranch        *b_xtdc_t_7_3;   //!
   TBranch        *b_ytdc_t_7_3;   //!
   TBranch        *b_xtdc_l_7_4;   //!
   TBranch        *b_ytdc_l_7_4;   //!
   TBranch        *b_xtdc_t_7_4;   //!
   TBranch        *b_ytdc_t_7_4;   //!
   TBranch        *b_xtdc_l_7_5;   //!
   TBranch        *b_ytdc_l_7_5;   //!
   TBranch        *b_xtdc_t_7_5;   //!
   TBranch        *b_ytdc_t_7_5;   //!
   TBranch        *b_xtdc_l_7_6;   //!
   TBranch        *b_ytdc_l_7_6;   //!
   TBranch        *b_xtdc_t_7_6;   //!
   TBranch        *b_ytdc_t_7_6;   //!
   TBranch        *b_xtdc_l_7_7;   //!
   TBranch        *b_ytdc_l_7_7;   //!
   TBranch        *b_xtdc_t_7_7;   //!
   TBranch        *b_ytdc_t_7_7;   //!
   TBranch        *b_xtdc_l_8_0;   //!
   TBranch        *b_ytdc_l_8_0;   //!
   TBranch        *b_xtdc_t_8_0;   //!
   TBranch        *b_ytdc_t_8_0;   //!
   TBranch        *b_xtdc_l_8_1;   //!
   TBranch        *b_ytdc_l_8_1;   //!
   TBranch        *b_xtdc_t_8_1;   //!
   TBranch        *b_ytdc_t_8_1;   //!
   TBranch        *b_xtdc_l_8_2;   //!
   TBranch        *b_ytdc_l_8_2;   //!
   TBranch        *b_xtdc_t_8_2;   //!
   TBranch        *b_ytdc_t_8_2;   //!
   TBranch        *b_xtdc_l_8_3;   //!
   TBranch        *b_ytdc_l_8_3;   //!
   TBranch        *b_xtdc_t_8_3;   //!
   TBranch        *b_ytdc_t_8_3;   //!
   TBranch        *b_xtdc_l_8_4;   //!
   TBranch        *b_ytdc_l_8_4;   //!
   TBranch        *b_xtdc_t_8_4;   //!
   TBranch        *b_ytdc_t_8_4;   //!
   TBranch        *b_xtdc_l_8_5;   //!
   TBranch        *b_ytdc_l_8_5;   //!
   TBranch        *b_xtdc_t_8_5;   //!
   TBranch        *b_ytdc_t_8_5;   //!
   TBranch        *b_xtdc_l_8_6;   //!
   TBranch        *b_ytdc_l_8_6;   //!
   TBranch        *b_xtdc_t_8_6;   //!
   TBranch        *b_ytdc_t_8_6;   //!
   TBranch        *b_xtdc_l_8_7;   //!
   TBranch        *b_ytdc_l_8_7;   //!
   TBranch        *b_xtdc_t_8_7;   //!
   TBranch        *b_ytdc_t_8_7;   //!
   TBranch        *b_xtdc_l_9_0;   //!
   TBranch        *b_ytdc_l_9_0;   //!
   TBranch        *b_xtdc_t_9_0;   //!
   TBranch        *b_ytdc_t_9_0;   //!
   TBranch        *b_xtdc_l_9_1;   //!
   TBranch        *b_ytdc_l_9_1;   //!
   TBranch        *b_xtdc_t_9_1;   //!
   TBranch        *b_ytdc_t_9_1;   //!
   TBranch        *b_xtdc_l_9_2;   //!
   TBranch        *b_ytdc_l_9_2;   //!
   TBranch        *b_xtdc_t_9_2;   //!
   TBranch        *b_ytdc_t_9_2;   //!
   TBranch        *b_xtdc_l_9_3;   //!
   TBranch        *b_ytdc_l_9_3;   //!
   TBranch        *b_xtdc_t_9_3;   //!
   TBranch        *b_ytdc_t_9_3;   //!
   TBranch        *b_xtdc_l_9_4;   //!
   TBranch        *b_ytdc_l_9_4;   //!
   TBranch        *b_xtdc_t_9_4;   //!
   TBranch        *b_ytdc_t_9_4;   //!
   TBranch        *b_xtdc_l_9_5;   //!
   TBranch        *b_ytdc_l_9_5;   //!
   TBranch        *b_xtdc_t_9_5;   //!
   TBranch        *b_ytdc_t_9_5;   //!
   TBranch        *b_xtdc_l_9_6;   //!
   TBranch        *b_ytdc_l_9_6;   //!
   TBranch        *b_xtdc_t_9_6;   //!
   TBranch        *b_ytdc_t_9_6;   //!
   TBranch        *b_xtdc_l_9_7;   //!
   TBranch        *b_ytdc_l_9_7;   //!
   TBranch        *b_xtdc_t_9_7;   //!
   TBranch        *b_ytdc_t_9_7;   //!
   TBranch        *b_xtdc_l_10_0;   //!
   TBranch        *b_ytdc_l_10_0;   //!
   TBranch        *b_xtdc_t_10_0;   //!
   TBranch        *b_ytdc_t_10_0;   //!
   TBranch        *b_xtdc_l_10_1;   //!
   TBranch        *b_ytdc_l_10_1;   //!
   TBranch        *b_xtdc_t_10_1;   //!
   TBranch        *b_ytdc_t_10_1;   //!
   TBranch        *b_xtdc_l_10_2;   //!
   TBranch        *b_ytdc_l_10_2;   //!
   TBranch        *b_xtdc_t_10_2;   //!
   TBranch        *b_ytdc_t_10_2;   //!
   TBranch        *b_xtdc_l_10_3;   //!
   TBranch        *b_ytdc_l_10_3;   //!
   TBranch        *b_xtdc_t_10_3;   //!
   TBranch        *b_ytdc_t_10_3;   //!
   TBranch        *b_xtdc_l_10_4;   //!
   TBranch        *b_ytdc_l_10_4;   //!
   TBranch        *b_xtdc_t_10_4;   //!
   TBranch        *b_ytdc_t_10_4;   //!
   TBranch        *b_xtdc_l_10_5;   //!
   TBranch        *b_ytdc_l_10_5;   //!
   TBranch        *b_xtdc_t_10_5;   //!
   TBranch        *b_ytdc_t_10_5;   //!
   TBranch        *b_xtdc_l_10_6;   //!
   TBranch        *b_ytdc_l_10_6;   //!
   TBranch        *b_xtdc_t_10_6;   //!
   TBranch        *b_ytdc_t_10_6;   //!
   TBranch        *b_xtdc_l_10_7;   //!
   TBranch        *b_ytdc_l_10_7;   //!
   TBranch        *b_xtdc_t_10_7;   //!
   TBranch        *b_ytdc_t_10_7;   //!
   TBranch        *b_xtdc_l_11_0;   //!
   TBranch        *b_ytdc_l_11_0;   //!
   TBranch        *b_xtdc_t_11_0;   //!
   TBranch        *b_ytdc_t_11_0;   //!
   TBranch        *b_xtdc_l_11_1;   //!
   TBranch        *b_ytdc_l_11_1;   //!
   TBranch        *b_xtdc_t_11_1;   //!
   TBranch        *b_ytdc_t_11_1;   //!
   TBranch        *b_xtdc_l_11_2;   //!
   TBranch        *b_ytdc_l_11_2;   //!
   TBranch        *b_xtdc_t_11_2;   //!
   TBranch        *b_ytdc_t_11_2;   //!
   TBranch        *b_xtdc_l_11_3;   //!
   TBranch        *b_ytdc_l_11_3;   //!
   TBranch        *b_xtdc_t_11_3;   //!
   TBranch        *b_ytdc_t_11_3;   //!
   TBranch        *b_xtdc_l_11_4;   //!
   TBranch        *b_ytdc_l_11_4;   //!
   TBranch        *b_xtdc_t_11_4;   //!
   TBranch        *b_ytdc_t_11_4;   //!
   TBranch        *b_xtdc_l_11_5;   //!
   TBranch        *b_ytdc_l_11_5;   //!
   TBranch        *b_xtdc_t_11_5;   //!
   TBranch        *b_ytdc_t_11_5;   //!
   TBranch        *b_xtdc_l_11_6;   //!
   TBranch        *b_ytdc_l_11_6;   //!
   TBranch        *b_xtdc_t_11_6;   //!
   TBranch        *b_ytdc_t_11_6;   //!
   TBranch        *b_xtdc_l_11_7;   //!
   TBranch        *b_ytdc_l_11_7;   //!
   TBranch        *b_xtdc_t_11_7;   //!
   TBranch        *b_ytdc_t_11_7;   //!

   TTimeStamp *EveTS[NL];
   TBits *xLayer[NL];
   TBits *yLayer[NL];
   std::vector<unsigned int> *vxtdc_l[NL][NC];
   std::vector<unsigned int> *vytdc_l[NL][NC];

   std::vector<unsigned int> *vxtdc_t[NL][NC];
   std::vector<unsigned int> *vytdc_t[NL][NC];

   RPCEve(TTree *tree=0);
   virtual ~RPCEve();
   virtual Int_t    Cut(Long64_t entry);
   virtual Int_t    GetEntry(Long64_t entry);
   virtual Long64_t LoadTree(Long64_t entry);
   virtual void     Init(TTree *tree);
   virtual void     Loop();
   virtual Bool_t   Notify();
   virtual void     Show(Long64_t entry = -1);
};

#endif

#ifdef RPCEve_cxx
RPCEve::RPCEve(TTree *tree) : fChain(0) 
{
// if parameter tree is not specified (or zero), connect the file
// used to generate this class and read the Tree.
   if (tree == 0) {
      TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("RPC_evtraw-r212230.dat");
      if (!f || !f->IsOpen()) {
         f = new TFile("RPC_evtraw-r212230.dat");
      }
      f->GetObject("evetree",tree);

   }
   Init(tree);
}

RPCEve::~RPCEve()
{
   if (!fChain) return;
   delete fChain->GetCurrentFile();
}

Int_t RPCEve::GetEntry(Long64_t entry)
{
// Read contents of entry.
   if (!fChain) return 0;
   return fChain->GetEntry(entry);
}
Long64_t RPCEve::LoadTree(Long64_t entry)
{
// Set the environment to read one entry
   if (!fChain) return -5;
   Long64_t centry = fChain->LoadTree(entry);
   if (centry < 0) return centry;
   if (fChain->GetTreeNumber() != fCurrent) {
      fCurrent = fChain->GetTreeNumber();
      Notify();
   }
   return centry;
}

void RPCEve::Init(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set object pointer
    Evetime_0 = 0;
    Evetime_1 = 0;
    Evetime_2 = 0;
    Evetime_3 = 0;
    Evetime_4 = 0;
    Evetime_5 = 0;
    Evetime_6 = 0;
    Evetime_7 = 0;
    Evetime_8 = 0;
    Evetime_9 = 0;
    Evetime_10 = 0;
    Evetime_11 = 0;

   xstriphitsL0 = 0;
   ystriphitsL0 = 0;
   xstriphitsL1 = 0;
   ystriphitsL1 = 0;
   xstriphitsL2 = 0;
   ystriphitsL2 = 0;
   xstriphitsL3 = 0;
   ystriphitsL3 = 0;
   xstriphitsL4 = 0;
   ystriphitsL4 = 0;
   xstriphitsL5 = 0;
   ystriphitsL5 = 0;
   xstriphitsL6 = 0;
   ystriphitsL6 = 0;
   xstriphitsL7 = 0;
   ystriphitsL7 = 0;
   xstriphitsL8 = 0;
   ystriphitsL8 = 0;
   xstriphitsL9 = 0;
   ystriphitsL9 = 0;
   xstriphitsL10 = 0;
   ystriphitsL10 = 0;
   xstriphitsL11 = 0;
   ystriphitsL11 = 0;
   xtdc_l_0_0 = 0;
   ytdc_l_0_0 = 0;
   xtdc_t_0_0 = 0;
   ytdc_t_0_0 = 0;
   xtdc_l_0_1 = 0;
   ytdc_l_0_1 = 0;
   xtdc_t_0_1 = 0;
   ytdc_t_0_1 = 0;
   xtdc_l_0_2 = 0;
   ytdc_l_0_2 = 0;
   xtdc_t_0_2 = 0;
   ytdc_t_0_2 = 0;
   xtdc_l_0_3 = 0;
   ytdc_l_0_3 = 0;
   xtdc_t_0_3 = 0;
   ytdc_t_0_3 = 0;
   xtdc_l_0_4 = 0;
   ytdc_l_0_4 = 0;
   xtdc_t_0_4 = 0;
   ytdc_t_0_4 = 0;
   xtdc_l_0_5 = 0;
   ytdc_l_0_5 = 0;
   xtdc_t_0_5 = 0;
   ytdc_t_0_5 = 0;
   xtdc_l_0_6 = 0;
   ytdc_l_0_6 = 0;
   xtdc_t_0_6 = 0;
   ytdc_t_0_6 = 0;
   xtdc_l_0_7 = 0;
   ytdc_l_0_7 = 0;
   xtdc_t_0_7 = 0;
   ytdc_t_0_7 = 0;
   xtdc_l_1_0 = 0;
   ytdc_l_1_0 = 0;
   xtdc_t_1_0 = 0;
   ytdc_t_1_0 = 0;
   xtdc_l_1_1 = 0;
   ytdc_l_1_1 = 0;
   xtdc_t_1_1 = 0;
   ytdc_t_1_1 = 0;
   xtdc_l_1_2 = 0;
   ytdc_l_1_2 = 0;
   xtdc_t_1_2 = 0;
   ytdc_t_1_2 = 0;
   xtdc_l_1_3 = 0;
   ytdc_l_1_3 = 0;
   xtdc_t_1_3 = 0;
   ytdc_t_1_3 = 0;
   xtdc_l_1_4 = 0;
   ytdc_l_1_4 = 0;
   xtdc_t_1_4 = 0;
   ytdc_t_1_4 = 0;
   xtdc_l_1_5 = 0;
   ytdc_l_1_5 = 0;
   xtdc_t_1_5 = 0;
   ytdc_t_1_5 = 0;
   xtdc_l_1_6 = 0;
   ytdc_l_1_6 = 0;
   xtdc_t_1_6 = 0;
   ytdc_t_1_6 = 0;
   xtdc_l_1_7 = 0;
   ytdc_l_1_7 = 0;
   xtdc_t_1_7 = 0;
   ytdc_t_1_7 = 0;
   xtdc_l_2_0 = 0;
   ytdc_l_2_0 = 0;
   xtdc_t_2_0 = 0;
   ytdc_t_2_0 = 0;
   xtdc_l_2_1 = 0;
   ytdc_l_2_1 = 0;
   xtdc_t_2_1 = 0;
   ytdc_t_2_1 = 0;
   xtdc_l_2_2 = 0;
   ytdc_l_2_2 = 0;
   xtdc_t_2_2 = 0;
   ytdc_t_2_2 = 0;
   xtdc_l_2_3 = 0;
   ytdc_l_2_3 = 0;
   xtdc_t_2_3 = 0;
   ytdc_t_2_3 = 0;
   xtdc_l_2_4 = 0;
   ytdc_l_2_4 = 0;
   xtdc_t_2_4 = 0;
   ytdc_t_2_4 = 0;
   xtdc_l_2_5 = 0;
   ytdc_l_2_5 = 0;
   xtdc_t_2_5 = 0;
   ytdc_t_2_5 = 0;
   xtdc_l_2_6 = 0;
   ytdc_l_2_6 = 0;
   xtdc_t_2_6 = 0;
   ytdc_t_2_6 = 0;
   xtdc_l_2_7 = 0;
   ytdc_l_2_7 = 0;
   xtdc_t_2_7 = 0;
   ytdc_t_2_7 = 0;
   xtdc_l_3_0 = 0;
   ytdc_l_3_0 = 0;
   xtdc_t_3_0 = 0;
   ytdc_t_3_0 = 0;
   xtdc_l_3_1 = 0;
   ytdc_l_3_1 = 0;
   xtdc_t_3_1 = 0;
   ytdc_t_3_1 = 0;
   xtdc_l_3_2 = 0;
   ytdc_l_3_2 = 0;
   xtdc_t_3_2 = 0;
   ytdc_t_3_2 = 0;
   xtdc_l_3_3 = 0;
   ytdc_l_3_3 = 0;
   xtdc_t_3_3 = 0;
   ytdc_t_3_3 = 0;
   xtdc_l_3_4 = 0;
   ytdc_l_3_4 = 0;
   xtdc_t_3_4 = 0;
   ytdc_t_3_4 = 0;
   xtdc_l_3_5 = 0;
   ytdc_l_3_5 = 0;
   xtdc_t_3_5 = 0;
   ytdc_t_3_5 = 0;
   xtdc_l_3_6 = 0;
   ytdc_l_3_6 = 0;
   xtdc_t_3_6 = 0;
   ytdc_t_3_6 = 0;
   xtdc_l_3_7 = 0;
   ytdc_l_3_7 = 0;
   xtdc_t_3_7 = 0;
   ytdc_t_3_7 = 0;
   xtdc_l_4_0 = 0;
   ytdc_l_4_0 = 0;
   xtdc_t_4_0 = 0;
   ytdc_t_4_0 = 0;
   xtdc_l_4_1 = 0;
   ytdc_l_4_1 = 0;
   xtdc_t_4_1 = 0;
   ytdc_t_4_1 = 0;
   xtdc_l_4_2 = 0;
   ytdc_l_4_2 = 0;
   xtdc_t_4_2 = 0;
   ytdc_t_4_2 = 0;
   xtdc_l_4_3 = 0;
   ytdc_l_4_3 = 0;
   xtdc_t_4_3 = 0;
   ytdc_t_4_3 = 0;
   xtdc_l_4_4 = 0;
   ytdc_l_4_4 = 0;
   xtdc_t_4_4 = 0;
   ytdc_t_4_4 = 0;
   xtdc_l_4_5 = 0;
   ytdc_l_4_5 = 0;
   xtdc_t_4_5 = 0;
   ytdc_t_4_5 = 0;
   xtdc_l_4_6 = 0;
   ytdc_l_4_6 = 0;
   xtdc_t_4_6 = 0;
   ytdc_t_4_6 = 0;
   xtdc_l_4_7 = 0;
   ytdc_l_4_7 = 0;
   xtdc_t_4_7 = 0;
   ytdc_t_4_7 = 0;
   xtdc_l_5_0 = 0;
   ytdc_l_5_0 = 0;
   xtdc_t_5_0 = 0;
   ytdc_t_5_0 = 0;
   xtdc_l_5_1 = 0;
   ytdc_l_5_1 = 0;
   xtdc_t_5_1 = 0;
   ytdc_t_5_1 = 0;
   xtdc_l_5_2 = 0;
   ytdc_l_5_2 = 0;
   xtdc_t_5_2 = 0;
   ytdc_t_5_2 = 0;
   xtdc_l_5_3 = 0;
   ytdc_l_5_3 = 0;
   xtdc_t_5_3 = 0;
   ytdc_t_5_3 = 0;
   xtdc_l_5_4 = 0;
   ytdc_l_5_4 = 0;
   xtdc_t_5_4 = 0;
   ytdc_t_5_4 = 0;
   xtdc_l_5_5 = 0;
   ytdc_l_5_5 = 0;
   xtdc_t_5_5 = 0;
   ytdc_t_5_5 = 0;
   xtdc_l_5_6 = 0;
   ytdc_l_5_6 = 0;
   xtdc_t_5_6 = 0;
   ytdc_t_5_6 = 0;
   xtdc_l_5_7 = 0;
   ytdc_l_5_7 = 0;
   xtdc_t_5_7 = 0;
   ytdc_t_5_7 = 0;
   xtdc_l_6_0 = 0;
   ytdc_l_6_0 = 0;
   xtdc_t_6_0 = 0;
   ytdc_t_6_0 = 0;
   xtdc_l_6_1 = 0;
   ytdc_l_6_1 = 0;
   xtdc_t_6_1 = 0;
   ytdc_t_6_1 = 0;
   xtdc_l_6_2 = 0;
   ytdc_l_6_2 = 0;
   xtdc_t_6_2 = 0;
   ytdc_t_6_2 = 0;
   xtdc_l_6_3 = 0;
   ytdc_l_6_3 = 0;
   xtdc_t_6_3 = 0;
   ytdc_t_6_3 = 0;
   xtdc_l_6_4 = 0;
   ytdc_l_6_4 = 0;
   xtdc_t_6_4 = 0;
   ytdc_t_6_4 = 0;
   xtdc_l_6_5 = 0;
   ytdc_l_6_5 = 0;
   xtdc_t_6_5 = 0;
   ytdc_t_6_5 = 0;
   xtdc_l_6_6 = 0;
   ytdc_l_6_6 = 0;
   xtdc_t_6_6 = 0;
   ytdc_t_6_6 = 0;
   xtdc_l_6_7 = 0;
   ytdc_l_6_7 = 0;
   xtdc_t_6_7 = 0;
   ytdc_t_6_7 = 0;
   xtdc_l_7_0 = 0;
   ytdc_l_7_0 = 0;
   xtdc_t_7_0 = 0;
   ytdc_t_7_0 = 0;
   xtdc_l_7_1 = 0;
   ytdc_l_7_1 = 0;
   xtdc_t_7_1 = 0;
   ytdc_t_7_1 = 0;
   xtdc_l_7_2 = 0;
   ytdc_l_7_2 = 0;
   xtdc_t_7_2 = 0;
   ytdc_t_7_2 = 0;
   xtdc_l_7_3 = 0;
   ytdc_l_7_3 = 0;
   xtdc_t_7_3 = 0;
   ytdc_t_7_3 = 0;
   xtdc_l_7_4 = 0;
   ytdc_l_7_4 = 0;
   xtdc_t_7_4 = 0;
   ytdc_t_7_4 = 0;
   xtdc_l_7_5 = 0;
   ytdc_l_7_5 = 0;
   xtdc_t_7_5 = 0;
   ytdc_t_7_5 = 0;
   xtdc_l_7_6 = 0;
   ytdc_l_7_6 = 0;
   xtdc_t_7_6 = 0;
   ytdc_t_7_6 = 0;
   xtdc_l_7_7 = 0;
   ytdc_l_7_7 = 0;
   xtdc_t_7_7 = 0;
   ytdc_t_7_7 = 0;
   xtdc_l_8_0 = 0;
   ytdc_l_8_0 = 0;
   xtdc_t_8_0 = 0;
   ytdc_t_8_0 = 0;
   xtdc_l_8_1 = 0;
   ytdc_l_8_1 = 0;
   xtdc_t_8_1 = 0;
   ytdc_t_8_1 = 0;
   xtdc_l_8_2 = 0;
   ytdc_l_8_2 = 0;
   xtdc_t_8_2 = 0;
   ytdc_t_8_2 = 0;
   xtdc_l_8_3 = 0;
   ytdc_l_8_3 = 0;
   xtdc_t_8_3 = 0;
   ytdc_t_8_3 = 0;
   xtdc_l_8_4 = 0;
   ytdc_l_8_4 = 0;
   xtdc_t_8_4 = 0;
   ytdc_t_8_4 = 0;
   xtdc_l_8_5 = 0;
   ytdc_l_8_5 = 0;
   xtdc_t_8_5 = 0;
   ytdc_t_8_5 = 0;
   xtdc_l_8_6 = 0;
   ytdc_l_8_6 = 0;
   xtdc_t_8_6 = 0;
   ytdc_t_8_6 = 0;
   xtdc_l_8_7 = 0;
   ytdc_l_8_7 = 0;
   xtdc_t_8_7 = 0;
   ytdc_t_8_7 = 0;
   xtdc_l_9_0 = 0;
   ytdc_l_9_0 = 0;
   xtdc_t_9_0 = 0;
   ytdc_t_9_0 = 0;
   xtdc_l_9_1 = 0;
   ytdc_l_9_1 = 0;
   xtdc_t_9_1 = 0;
   ytdc_t_9_1 = 0;
   xtdc_l_9_2 = 0;
   ytdc_l_9_2 = 0;
   xtdc_t_9_2 = 0;
   ytdc_t_9_2 = 0;
   xtdc_l_9_3 = 0;
   ytdc_l_9_3 = 0;
   xtdc_t_9_3 = 0;
   ytdc_t_9_3 = 0;
   xtdc_l_9_4 = 0;
   ytdc_l_9_4 = 0;
   xtdc_t_9_4 = 0;
   ytdc_t_9_4 = 0;
   xtdc_l_9_5 = 0;
   ytdc_l_9_5 = 0;
   xtdc_t_9_5 = 0;
   ytdc_t_9_5 = 0;
   xtdc_l_9_6 = 0;
   ytdc_l_9_6 = 0;
   xtdc_t_9_6 = 0;
   ytdc_t_9_6 = 0;
   xtdc_l_9_7 = 0;
   ytdc_l_9_7 = 0;
   xtdc_t_9_7 = 0;
   ytdc_t_9_7 = 0;
   xtdc_l_10_0 = 0;
   ytdc_l_10_0 = 0;
   xtdc_t_10_0 = 0;
   ytdc_t_10_0 = 0;
   xtdc_l_10_1 = 0;
   ytdc_l_10_1 = 0;
   xtdc_t_10_1 = 0;
   ytdc_t_10_1 = 0;
   xtdc_l_10_2 = 0;
   ytdc_l_10_2 = 0;
   xtdc_t_10_2 = 0;
   ytdc_t_10_2 = 0;
   xtdc_l_10_3 = 0;
   ytdc_l_10_3 = 0;
   xtdc_t_10_3 = 0;
   ytdc_t_10_3 = 0;
   xtdc_l_10_4 = 0;
   ytdc_l_10_4 = 0;
   xtdc_t_10_4 = 0;
   ytdc_t_10_4 = 0;
   xtdc_l_10_5 = 0;
   ytdc_l_10_5 = 0;
   xtdc_t_10_5 = 0;
   ytdc_t_10_5 = 0;
   xtdc_l_10_6 = 0;
   ytdc_l_10_6 = 0;
   xtdc_t_10_6 = 0;
   ytdc_t_10_6 = 0;
   xtdc_l_10_7 = 0;
   ytdc_l_10_7 = 0;
   xtdc_t_10_7 = 0;
   ytdc_t_10_7 = 0;
   xtdc_l_11_0 = 0;
   ytdc_l_11_0 = 0;
   xtdc_t_11_0 = 0;
   ytdc_t_11_0 = 0;
   xtdc_l_11_1 = 0;
   ytdc_l_11_1 = 0;
   xtdc_t_11_1 = 0;
   ytdc_t_11_1 = 0;
   xtdc_l_11_2 = 0;
   ytdc_l_11_2 = 0;
   xtdc_t_11_2 = 0;
   ytdc_t_11_2 = 0;
   xtdc_l_11_3 = 0;
   ytdc_l_11_3 = 0;
   xtdc_t_11_3 = 0;
   ytdc_t_11_3 = 0;
   xtdc_l_11_4 = 0;
   ytdc_l_11_4 = 0;
   xtdc_t_11_4 = 0;
   ytdc_t_11_4 = 0;
   xtdc_l_11_5 = 0;
   ytdc_l_11_5 = 0;
   xtdc_t_11_5 = 0;
   ytdc_t_11_5 = 0;
   xtdc_l_11_6 = 0;
   ytdc_l_11_6 = 0;
   xtdc_t_11_6 = 0;
   ytdc_t_11_6 = 0;
   xtdc_l_11_7 = 0;
   ytdc_l_11_7 = 0;
   xtdc_t_11_7 = 0;
   ytdc_t_11_7 = 0;
   // Set branch addresses and branch pointers
   if (!tree) return;
   fChain = tree;
   fCurrent = -1;
   fChain->SetMakeClass(1);

   fChain->SetBranchAddress("ENum", &ENum, &b_ENum);
   fChain->SetBranchAddress("REnum", &REnum, &b_REnum);
   fChain->SetBranchAddress("CEnum", &CEnum, &b_CEnum);
   fChain->SetBranchAddress("Evetime_0", &Evetime_0, &b_Evetime_0);
   fChain->SetBranchAddress("Evetime_1", &Evetime_1, &b_Evetime_1);
   fChain->SetBranchAddress("Evetime_2", &Evetime_2, &b_Evetime_2);
   fChain->SetBranchAddress("Evetime_3", &Evetime_3, &b_Evetime_3);
   fChain->SetBranchAddress("Evetime_4", &Evetime_4, &b_Evetime_4);
   fChain->SetBranchAddress("Evetime_5", &Evetime_5, &b_Evetime_5);
   fChain->SetBranchAddress("Evetime_6", &Evetime_6, &b_Evetime_6);
   fChain->SetBranchAddress("Evetime_7", &Evetime_7, &b_Evetime_7);
   fChain->SetBranchAddress("Evetime_8", &Evetime_8, &b_Evetime_8);
   fChain->SetBranchAddress("Evetime_9", &Evetime_9, &b_Evetime_9);
   fChain->SetBranchAddress("Evetime_10", &Evetime_10, &b_Evetime_10);
   fChain->SetBranchAddress("Evetime_11", &Evetime_11, &b_Evetime_11);

   fChain->SetBranchAddress("xstriphitsL0", &xstriphitsL0, &b_xstriphitsL0);
   fChain->SetBranchAddress("ystriphitsL0", &ystriphitsL0, &b_ystriphitsL0);
   fChain->SetBranchAddress("xstriphitsL1", &xstriphitsL1, &b_xstriphitsL1);
   fChain->SetBranchAddress("ystriphitsL1", &ystriphitsL1, &b_ystriphitsL1);
   fChain->SetBranchAddress("xstriphitsL2", &xstriphitsL2, &b_xstriphitsL2);
   fChain->SetBranchAddress("ystriphitsL2", &ystriphitsL2, &b_ystriphitsL2);
   fChain->SetBranchAddress("xstriphitsL3", &xstriphitsL3, &b_xstriphitsL3);
   fChain->SetBranchAddress("ystriphitsL3", &ystriphitsL3, &b_ystriphitsL3);
   fChain->SetBranchAddress("xstriphitsL4", &xstriphitsL4, &b_xstriphitsL4);
   fChain->SetBranchAddress("ystriphitsL4", &ystriphitsL4, &b_ystriphitsL4);
   fChain->SetBranchAddress("xstriphitsL5", &xstriphitsL5, &b_xstriphitsL5);
   fChain->SetBranchAddress("ystriphitsL5", &ystriphitsL5, &b_ystriphitsL5);
   fChain->SetBranchAddress("xstriphitsL6", &xstriphitsL6, &b_xstriphitsL6);
   fChain->SetBranchAddress("ystriphitsL6", &ystriphitsL6, &b_ystriphitsL6);
   fChain->SetBranchAddress("xstriphitsL7", &xstriphitsL7, &b_xstriphitsL7);
   fChain->SetBranchAddress("ystriphitsL7", &ystriphitsL7, &b_ystriphitsL7);
   fChain->SetBranchAddress("xstriphitsL8", &xstriphitsL8, &b_xstriphitsL8);
   fChain->SetBranchAddress("ystriphitsL8", &ystriphitsL8, &b_ystriphitsL8);
   fChain->SetBranchAddress("xstriphitsL9", &xstriphitsL9, &b_xstriphitsL9);
   fChain->SetBranchAddress("ystriphitsL9", &ystriphitsL9, &b_ystriphitsL9);
   fChain->SetBranchAddress("xstriphitsL10", &xstriphitsL10, &b_xstriphitsL10);
   fChain->SetBranchAddress("ystriphitsL10", &ystriphitsL10, &b_ystriphitsL10);
   fChain->SetBranchAddress("xstriphitsL11", &xstriphitsL11, &b_xstriphitsL11);
   fChain->SetBranchAddress("ystriphitsL11", &ystriphitsL11, &b_ystriphitsL11);
   fChain->SetBranchAddress("tdc_ref_l", tdc_ref_l, &b_tdc_ref_l);
   fChain->SetBranchAddress("tdc_ref_t", tdc_ref_t, &b_tdc_ref_t);
   //add here for trigger count difference
   fChain->SetBranchAddress("trigCntDiff", trigCntDiff, &b_trigCntDiff);
   fChain->SetBranchAddress("xtdc_l_0_0", &xtdc_l_0_0, &b_xtdc_l_0_0);
   fChain->SetBranchAddress("ytdc_l_0_0", &ytdc_l_0_0, &b_ytdc_l_0_0);
   fChain->SetBranchAddress("xtdc_t_0_0", &xtdc_t_0_0, &b_xtdc_t_0_0);
   fChain->SetBranchAddress("ytdc_t_0_0", &ytdc_t_0_0, &b_ytdc_t_0_0);
   fChain->SetBranchAddress("xtdc_l_0_1", &xtdc_l_0_1, &b_xtdc_l_0_1);
   fChain->SetBranchAddress("ytdc_l_0_1", &ytdc_l_0_1, &b_ytdc_l_0_1);
   fChain->SetBranchAddress("xtdc_t_0_1", &xtdc_t_0_1, &b_xtdc_t_0_1);
   fChain->SetBranchAddress("ytdc_t_0_1", &ytdc_t_0_1, &b_ytdc_t_0_1);
   fChain->SetBranchAddress("xtdc_l_0_2", &xtdc_l_0_2, &b_xtdc_l_0_2);
   fChain->SetBranchAddress("ytdc_l_0_2", &ytdc_l_0_2, &b_ytdc_l_0_2);
   fChain->SetBranchAddress("xtdc_t_0_2", &xtdc_t_0_2, &b_xtdc_t_0_2);
   fChain->SetBranchAddress("ytdc_t_0_2", &ytdc_t_0_2, &b_ytdc_t_0_2);
   fChain->SetBranchAddress("xtdc_l_0_3", &xtdc_l_0_3, &b_xtdc_l_0_3);
   fChain->SetBranchAddress("ytdc_l_0_3", &ytdc_l_0_3, &b_ytdc_l_0_3);
   fChain->SetBranchAddress("xtdc_t_0_3", &xtdc_t_0_3, &b_xtdc_t_0_3);
   fChain->SetBranchAddress("ytdc_t_0_3", &ytdc_t_0_3, &b_ytdc_t_0_3);
   fChain->SetBranchAddress("xtdc_l_0_4", &xtdc_l_0_4, &b_xtdc_l_0_4);
   fChain->SetBranchAddress("ytdc_l_0_4", &ytdc_l_0_4, &b_ytdc_l_0_4);
   fChain->SetBranchAddress("xtdc_t_0_4", &xtdc_t_0_4, &b_xtdc_t_0_4);
   fChain->SetBranchAddress("ytdc_t_0_4", &ytdc_t_0_4, &b_ytdc_t_0_4);
   fChain->SetBranchAddress("xtdc_l_0_5", &xtdc_l_0_5, &b_xtdc_l_0_5);
   fChain->SetBranchAddress("ytdc_l_0_5", &ytdc_l_0_5, &b_ytdc_l_0_5);
   fChain->SetBranchAddress("xtdc_t_0_5", &xtdc_t_0_5, &b_xtdc_t_0_5);
   fChain->SetBranchAddress("ytdc_t_0_5", &ytdc_t_0_5, &b_ytdc_t_0_5);
   fChain->SetBranchAddress("xtdc_l_0_6", &xtdc_l_0_6, &b_xtdc_l_0_6);
   fChain->SetBranchAddress("ytdc_l_0_6", &ytdc_l_0_6, &b_ytdc_l_0_6);
   fChain->SetBranchAddress("xtdc_t_0_6", &xtdc_t_0_6, &b_xtdc_t_0_6);
   fChain->SetBranchAddress("ytdc_t_0_6", &ytdc_t_0_6, &b_ytdc_t_0_6);
   fChain->SetBranchAddress("xtdc_l_0_7", &xtdc_l_0_7, &b_xtdc_l_0_7);
   fChain->SetBranchAddress("ytdc_l_0_7", &ytdc_l_0_7, &b_ytdc_l_0_7);
   fChain->SetBranchAddress("xtdc_t_0_7", &xtdc_t_0_7, &b_xtdc_t_0_7);
   fChain->SetBranchAddress("ytdc_t_0_7", &ytdc_t_0_7, &b_ytdc_t_0_7);
   fChain->SetBranchAddress("xtdc_l_1_0", &xtdc_l_1_0, &b_xtdc_l_1_0);
   fChain->SetBranchAddress("ytdc_l_1_0", &ytdc_l_1_0, &b_ytdc_l_1_0);
   fChain->SetBranchAddress("xtdc_t_1_0", &xtdc_t_1_0, &b_xtdc_t_1_0);
   fChain->SetBranchAddress("ytdc_t_1_0", &ytdc_t_1_0, &b_ytdc_t_1_0);
   fChain->SetBranchAddress("xtdc_l_1_1", &xtdc_l_1_1, &b_xtdc_l_1_1);
   fChain->SetBranchAddress("ytdc_l_1_1", &ytdc_l_1_1, &b_ytdc_l_1_1);
   fChain->SetBranchAddress("xtdc_t_1_1", &xtdc_t_1_1, &b_xtdc_t_1_1);
   fChain->SetBranchAddress("ytdc_t_1_1", &ytdc_t_1_1, &b_ytdc_t_1_1);
   fChain->SetBranchAddress("xtdc_l_1_2", &xtdc_l_1_2, &b_xtdc_l_1_2);
   fChain->SetBranchAddress("ytdc_l_1_2", &ytdc_l_1_2, &b_ytdc_l_1_2);
   fChain->SetBranchAddress("xtdc_t_1_2", &xtdc_t_1_2, &b_xtdc_t_1_2);
   fChain->SetBranchAddress("ytdc_t_1_2", &ytdc_t_1_2, &b_ytdc_t_1_2);
   fChain->SetBranchAddress("xtdc_l_1_3", &xtdc_l_1_3, &b_xtdc_l_1_3);
   fChain->SetBranchAddress("ytdc_l_1_3", &ytdc_l_1_3, &b_ytdc_l_1_3);
   fChain->SetBranchAddress("xtdc_t_1_3", &xtdc_t_1_3, &b_xtdc_t_1_3);
   fChain->SetBranchAddress("ytdc_t_1_3", &ytdc_t_1_3, &b_ytdc_t_1_3);
   fChain->SetBranchAddress("xtdc_l_1_4", &xtdc_l_1_4, &b_xtdc_l_1_4);
   fChain->SetBranchAddress("ytdc_l_1_4", &ytdc_l_1_4, &b_ytdc_l_1_4);
   fChain->SetBranchAddress("xtdc_t_1_4", &xtdc_t_1_4, &b_xtdc_t_1_4);
   fChain->SetBranchAddress("ytdc_t_1_4", &ytdc_t_1_4, &b_ytdc_t_1_4);
   fChain->SetBranchAddress("xtdc_l_1_5", &xtdc_l_1_5, &b_xtdc_l_1_5);
   fChain->SetBranchAddress("ytdc_l_1_5", &ytdc_l_1_5, &b_ytdc_l_1_5);
   fChain->SetBranchAddress("xtdc_t_1_5", &xtdc_t_1_5, &b_xtdc_t_1_5);
   fChain->SetBranchAddress("ytdc_t_1_5", &ytdc_t_1_5, &b_ytdc_t_1_5);
   fChain->SetBranchAddress("xtdc_l_1_6", &xtdc_l_1_6, &b_xtdc_l_1_6);
   fChain->SetBranchAddress("ytdc_l_1_6", &ytdc_l_1_6, &b_ytdc_l_1_6);
   fChain->SetBranchAddress("xtdc_t_1_6", &xtdc_t_1_6, &b_xtdc_t_1_6);
   fChain->SetBranchAddress("ytdc_t_1_6", &ytdc_t_1_6, &b_ytdc_t_1_6);
   fChain->SetBranchAddress("xtdc_l_1_7", &xtdc_l_1_7, &b_xtdc_l_1_7);
   fChain->SetBranchAddress("ytdc_l_1_7", &ytdc_l_1_7, &b_ytdc_l_1_7);
   fChain->SetBranchAddress("xtdc_t_1_7", &xtdc_t_1_7, &b_xtdc_t_1_7);
   fChain->SetBranchAddress("ytdc_t_1_7", &ytdc_t_1_7, &b_ytdc_t_1_7);
   fChain->SetBranchAddress("xtdc_l_2_0", &xtdc_l_2_0, &b_xtdc_l_2_0);
   fChain->SetBranchAddress("ytdc_l_2_0", &ytdc_l_2_0, &b_ytdc_l_2_0);
   fChain->SetBranchAddress("xtdc_t_2_0", &xtdc_t_2_0, &b_xtdc_t_2_0);
   fChain->SetBranchAddress("ytdc_t_2_0", &ytdc_t_2_0, &b_ytdc_t_2_0);
   fChain->SetBranchAddress("xtdc_l_2_1", &xtdc_l_2_1, &b_xtdc_l_2_1);
   fChain->SetBranchAddress("ytdc_l_2_1", &ytdc_l_2_1, &b_ytdc_l_2_1);
   fChain->SetBranchAddress("xtdc_t_2_1", &xtdc_t_2_1, &b_xtdc_t_2_1);
   fChain->SetBranchAddress("ytdc_t_2_1", &ytdc_t_2_1, &b_ytdc_t_2_1);
   fChain->SetBranchAddress("xtdc_l_2_2", &xtdc_l_2_2, &b_xtdc_l_2_2);
   fChain->SetBranchAddress("ytdc_l_2_2", &ytdc_l_2_2, &b_ytdc_l_2_2);
   fChain->SetBranchAddress("xtdc_t_2_2", &xtdc_t_2_2, &b_xtdc_t_2_2);
   fChain->SetBranchAddress("ytdc_t_2_2", &ytdc_t_2_2, &b_ytdc_t_2_2);
   fChain->SetBranchAddress("xtdc_l_2_3", &xtdc_l_2_3, &b_xtdc_l_2_3);
   fChain->SetBranchAddress("ytdc_l_2_3", &ytdc_l_2_3, &b_ytdc_l_2_3);
   fChain->SetBranchAddress("xtdc_t_2_3", &xtdc_t_2_3, &b_xtdc_t_2_3);
   fChain->SetBranchAddress("ytdc_t_2_3", &ytdc_t_2_3, &b_ytdc_t_2_3);
   fChain->SetBranchAddress("xtdc_l_2_4", &xtdc_l_2_4, &b_xtdc_l_2_4);
   fChain->SetBranchAddress("ytdc_l_2_4", &ytdc_l_2_4, &b_ytdc_l_2_4);
   fChain->SetBranchAddress("xtdc_t_2_4", &xtdc_t_2_4, &b_xtdc_t_2_4);
   fChain->SetBranchAddress("ytdc_t_2_4", &ytdc_t_2_4, &b_ytdc_t_2_4);
   fChain->SetBranchAddress("xtdc_l_2_5", &xtdc_l_2_5, &b_xtdc_l_2_5);
   fChain->SetBranchAddress("ytdc_l_2_5", &ytdc_l_2_5, &b_ytdc_l_2_5);
   fChain->SetBranchAddress("xtdc_t_2_5", &xtdc_t_2_5, &b_xtdc_t_2_5);
   fChain->SetBranchAddress("ytdc_t_2_5", &ytdc_t_2_5, &b_ytdc_t_2_5);
   fChain->SetBranchAddress("xtdc_l_2_6", &xtdc_l_2_6, &b_xtdc_l_2_6);
   fChain->SetBranchAddress("ytdc_l_2_6", &ytdc_l_2_6, &b_ytdc_l_2_6);
   fChain->SetBranchAddress("xtdc_t_2_6", &xtdc_t_2_6, &b_xtdc_t_2_6);
   fChain->SetBranchAddress("ytdc_t_2_6", &ytdc_t_2_6, &b_ytdc_t_2_6);
   fChain->SetBranchAddress("xtdc_l_2_7", &xtdc_l_2_7, &b_xtdc_l_2_7);
   fChain->SetBranchAddress("ytdc_l_2_7", &ytdc_l_2_7, &b_ytdc_l_2_7);
   fChain->SetBranchAddress("xtdc_t_2_7", &xtdc_t_2_7, &b_xtdc_t_2_7);
   fChain->SetBranchAddress("ytdc_t_2_7", &ytdc_t_2_7, &b_ytdc_t_2_7);
   fChain->SetBranchAddress("xtdc_l_3_0", &xtdc_l_3_0, &b_xtdc_l_3_0);
   fChain->SetBranchAddress("ytdc_l_3_0", &ytdc_l_3_0, &b_ytdc_l_3_0);
   fChain->SetBranchAddress("xtdc_t_3_0", &xtdc_t_3_0, &b_xtdc_t_3_0);
   fChain->SetBranchAddress("ytdc_t_3_0", &ytdc_t_3_0, &b_ytdc_t_3_0);
   fChain->SetBranchAddress("xtdc_l_3_1", &xtdc_l_3_1, &b_xtdc_l_3_1);
   fChain->SetBranchAddress("ytdc_l_3_1", &ytdc_l_3_1, &b_ytdc_l_3_1);
   fChain->SetBranchAddress("xtdc_t_3_1", &xtdc_t_3_1, &b_xtdc_t_3_1);
   fChain->SetBranchAddress("ytdc_t_3_1", &ytdc_t_3_1, &b_ytdc_t_3_1);
   fChain->SetBranchAddress("xtdc_l_3_2", &xtdc_l_3_2, &b_xtdc_l_3_2);
   fChain->SetBranchAddress("ytdc_l_3_2", &ytdc_l_3_2, &b_ytdc_l_3_2);
   fChain->SetBranchAddress("xtdc_t_3_2", &xtdc_t_3_2, &b_xtdc_t_3_2);
   fChain->SetBranchAddress("ytdc_t_3_2", &ytdc_t_3_2, &b_ytdc_t_3_2);
   fChain->SetBranchAddress("xtdc_l_3_3", &xtdc_l_3_3, &b_xtdc_l_3_3);
   fChain->SetBranchAddress("ytdc_l_3_3", &ytdc_l_3_3, &b_ytdc_l_3_3);
   fChain->SetBranchAddress("xtdc_t_3_3", &xtdc_t_3_3, &b_xtdc_t_3_3);
   fChain->SetBranchAddress("ytdc_t_3_3", &ytdc_t_3_3, &b_ytdc_t_3_3);
   fChain->SetBranchAddress("xtdc_l_3_4", &xtdc_l_3_4, &b_xtdc_l_3_4);
   fChain->SetBranchAddress("ytdc_l_3_4", &ytdc_l_3_4, &b_ytdc_l_3_4);
   fChain->SetBranchAddress("xtdc_t_3_4", &xtdc_t_3_4, &b_xtdc_t_3_4);
   fChain->SetBranchAddress("ytdc_t_3_4", &ytdc_t_3_4, &b_ytdc_t_3_4);
   fChain->SetBranchAddress("xtdc_l_3_5", &xtdc_l_3_5, &b_xtdc_l_3_5);
   fChain->SetBranchAddress("ytdc_l_3_5", &ytdc_l_3_5, &b_ytdc_l_3_5);
   fChain->SetBranchAddress("xtdc_t_3_5", &xtdc_t_3_5, &b_xtdc_t_3_5);
   fChain->SetBranchAddress("ytdc_t_3_5", &ytdc_t_3_5, &b_ytdc_t_3_5);
   fChain->SetBranchAddress("xtdc_l_3_6", &xtdc_l_3_6, &b_xtdc_l_3_6);
   fChain->SetBranchAddress("ytdc_l_3_6", &ytdc_l_3_6, &b_ytdc_l_3_6);
   fChain->SetBranchAddress("xtdc_t_3_6", &xtdc_t_3_6, &b_xtdc_t_3_6);
   fChain->SetBranchAddress("ytdc_t_3_6", &ytdc_t_3_6, &b_ytdc_t_3_6);
   fChain->SetBranchAddress("xtdc_l_3_7", &xtdc_l_3_7, &b_xtdc_l_3_7);
   fChain->SetBranchAddress("ytdc_l_3_7", &ytdc_l_3_7, &b_ytdc_l_3_7);
   fChain->SetBranchAddress("xtdc_t_3_7", &xtdc_t_3_7, &b_xtdc_t_3_7);
   fChain->SetBranchAddress("ytdc_t_3_7", &ytdc_t_3_7, &b_ytdc_t_3_7);
   fChain->SetBranchAddress("xtdc_l_4_0", &xtdc_l_4_0, &b_xtdc_l_4_0);
   fChain->SetBranchAddress("ytdc_l_4_0", &ytdc_l_4_0, &b_ytdc_l_4_0);
   fChain->SetBranchAddress("xtdc_t_4_0", &xtdc_t_4_0, &b_xtdc_t_4_0);
   fChain->SetBranchAddress("ytdc_t_4_0", &ytdc_t_4_0, &b_ytdc_t_4_0);
   fChain->SetBranchAddress("xtdc_l_4_1", &xtdc_l_4_1, &b_xtdc_l_4_1);
   fChain->SetBranchAddress("ytdc_l_4_1", &ytdc_l_4_1, &b_ytdc_l_4_1);
   fChain->SetBranchAddress("xtdc_t_4_1", &xtdc_t_4_1, &b_xtdc_t_4_1);
   fChain->SetBranchAddress("ytdc_t_4_1", &ytdc_t_4_1, &b_ytdc_t_4_1);
   fChain->SetBranchAddress("xtdc_l_4_2", &xtdc_l_4_2, &b_xtdc_l_4_2);
   fChain->SetBranchAddress("ytdc_l_4_2", &ytdc_l_4_2, &b_ytdc_l_4_2);
   fChain->SetBranchAddress("xtdc_t_4_2", &xtdc_t_4_2, &b_xtdc_t_4_2);
   fChain->SetBranchAddress("ytdc_t_4_2", &ytdc_t_4_2, &b_ytdc_t_4_2);
   fChain->SetBranchAddress("xtdc_l_4_3", &xtdc_l_4_3, &b_xtdc_l_4_3);
   fChain->SetBranchAddress("ytdc_l_4_3", &ytdc_l_4_3, &b_ytdc_l_4_3);
   fChain->SetBranchAddress("xtdc_t_4_3", &xtdc_t_4_3, &b_xtdc_t_4_3);
   fChain->SetBranchAddress("ytdc_t_4_3", &ytdc_t_4_3, &b_ytdc_t_4_3);
   fChain->SetBranchAddress("xtdc_l_4_4", &xtdc_l_4_4, &b_xtdc_l_4_4);
   fChain->SetBranchAddress("ytdc_l_4_4", &ytdc_l_4_4, &b_ytdc_l_4_4);
   fChain->SetBranchAddress("xtdc_t_4_4", &xtdc_t_4_4, &b_xtdc_t_4_4);
   fChain->SetBranchAddress("ytdc_t_4_4", &ytdc_t_4_4, &b_ytdc_t_4_4);
   fChain->SetBranchAddress("xtdc_l_4_5", &xtdc_l_4_5, &b_xtdc_l_4_5);
   fChain->SetBranchAddress("ytdc_l_4_5", &ytdc_l_4_5, &b_ytdc_l_4_5);
   fChain->SetBranchAddress("xtdc_t_4_5", &xtdc_t_4_5, &b_xtdc_t_4_5);
   fChain->SetBranchAddress("ytdc_t_4_5", &ytdc_t_4_5, &b_ytdc_t_4_5);
   fChain->SetBranchAddress("xtdc_l_4_6", &xtdc_l_4_6, &b_xtdc_l_4_6);
   fChain->SetBranchAddress("ytdc_l_4_6", &ytdc_l_4_6, &b_ytdc_l_4_6);
   fChain->SetBranchAddress("xtdc_t_4_6", &xtdc_t_4_6, &b_xtdc_t_4_6);
   fChain->SetBranchAddress("ytdc_t_4_6", &ytdc_t_4_6, &b_ytdc_t_4_6);
   fChain->SetBranchAddress("xtdc_l_4_7", &xtdc_l_4_7, &b_xtdc_l_4_7);
   fChain->SetBranchAddress("ytdc_l_4_7", &ytdc_l_4_7, &b_ytdc_l_4_7);
   fChain->SetBranchAddress("xtdc_t_4_7", &xtdc_t_4_7, &b_xtdc_t_4_7);
   fChain->SetBranchAddress("ytdc_t_4_7", &ytdc_t_4_7, &b_ytdc_t_4_7);
   fChain->SetBranchAddress("xtdc_l_5_0", &xtdc_l_5_0, &b_xtdc_l_5_0);
   fChain->SetBranchAddress("ytdc_l_5_0", &ytdc_l_5_0, &b_ytdc_l_5_0);
   fChain->SetBranchAddress("xtdc_t_5_0", &xtdc_t_5_0, &b_xtdc_t_5_0);
   fChain->SetBranchAddress("ytdc_t_5_0", &ytdc_t_5_0, &b_ytdc_t_5_0);
   fChain->SetBranchAddress("xtdc_l_5_1", &xtdc_l_5_1, &b_xtdc_l_5_1);
   fChain->SetBranchAddress("ytdc_l_5_1", &ytdc_l_5_1, &b_ytdc_l_5_1);
   fChain->SetBranchAddress("xtdc_t_5_1", &xtdc_t_5_1, &b_xtdc_t_5_1);
   fChain->SetBranchAddress("ytdc_t_5_1", &ytdc_t_5_1, &b_ytdc_t_5_1);
   fChain->SetBranchAddress("xtdc_l_5_2", &xtdc_l_5_2, &b_xtdc_l_5_2);
   fChain->SetBranchAddress("ytdc_l_5_2", &ytdc_l_5_2, &b_ytdc_l_5_2);
   fChain->SetBranchAddress("xtdc_t_5_2", &xtdc_t_5_2, &b_xtdc_t_5_2);
   fChain->SetBranchAddress("ytdc_t_5_2", &ytdc_t_5_2, &b_ytdc_t_5_2);
   fChain->SetBranchAddress("xtdc_l_5_3", &xtdc_l_5_3, &b_xtdc_l_5_3);
   fChain->SetBranchAddress("ytdc_l_5_3", &ytdc_l_5_3, &b_ytdc_l_5_3);
   fChain->SetBranchAddress("xtdc_t_5_3", &xtdc_t_5_3, &b_xtdc_t_5_3);
   fChain->SetBranchAddress("ytdc_t_5_3", &ytdc_t_5_3, &b_ytdc_t_5_3);
   fChain->SetBranchAddress("xtdc_l_5_4", &xtdc_l_5_4, &b_xtdc_l_5_4);
   fChain->SetBranchAddress("ytdc_l_5_4", &ytdc_l_5_4, &b_ytdc_l_5_4);
   fChain->SetBranchAddress("xtdc_t_5_4", &xtdc_t_5_4, &b_xtdc_t_5_4);
   fChain->SetBranchAddress("ytdc_t_5_4", &ytdc_t_5_4, &b_ytdc_t_5_4);
   fChain->SetBranchAddress("xtdc_l_5_5", &xtdc_l_5_5, &b_xtdc_l_5_5);
   fChain->SetBranchAddress("ytdc_l_5_5", &ytdc_l_5_5, &b_ytdc_l_5_5);
   fChain->SetBranchAddress("xtdc_t_5_5", &xtdc_t_5_5, &b_xtdc_t_5_5);
   fChain->SetBranchAddress("ytdc_t_5_5", &ytdc_t_5_5, &b_ytdc_t_5_5);
   fChain->SetBranchAddress("xtdc_l_5_6", &xtdc_l_5_6, &b_xtdc_l_5_6);
   fChain->SetBranchAddress("ytdc_l_5_6", &ytdc_l_5_6, &b_ytdc_l_5_6);
   fChain->SetBranchAddress("xtdc_t_5_6", &xtdc_t_5_6, &b_xtdc_t_5_6);
   fChain->SetBranchAddress("ytdc_t_5_6", &ytdc_t_5_6, &b_ytdc_t_5_6);
   fChain->SetBranchAddress("xtdc_l_5_7", &xtdc_l_5_7, &b_xtdc_l_5_7);
   fChain->SetBranchAddress("ytdc_l_5_7", &ytdc_l_5_7, &b_ytdc_l_5_7);
   fChain->SetBranchAddress("xtdc_t_5_7", &xtdc_t_5_7, &b_xtdc_t_5_7);
   fChain->SetBranchAddress("ytdc_t_5_7", &ytdc_t_5_7, &b_ytdc_t_5_7);
   fChain->SetBranchAddress("xtdc_l_6_0", &xtdc_l_6_0, &b_xtdc_l_6_0);
   fChain->SetBranchAddress("ytdc_l_6_0", &ytdc_l_6_0, &b_ytdc_l_6_0);
   fChain->SetBranchAddress("xtdc_t_6_0", &xtdc_t_6_0, &b_xtdc_t_6_0);
   fChain->SetBranchAddress("ytdc_t_6_0", &ytdc_t_6_0, &b_ytdc_t_6_0);
   fChain->SetBranchAddress("xtdc_l_6_1", &xtdc_l_6_1, &b_xtdc_l_6_1);
   fChain->SetBranchAddress("ytdc_l_6_1", &ytdc_l_6_1, &b_ytdc_l_6_1);
   fChain->SetBranchAddress("xtdc_t_6_1", &xtdc_t_6_1, &b_xtdc_t_6_1);
   fChain->SetBranchAddress("ytdc_t_6_1", &ytdc_t_6_1, &b_ytdc_t_6_1);
   fChain->SetBranchAddress("xtdc_l_6_2", &xtdc_l_6_2, &b_xtdc_l_6_2);
   fChain->SetBranchAddress("ytdc_l_6_2", &ytdc_l_6_2, &b_ytdc_l_6_2);
   fChain->SetBranchAddress("xtdc_t_6_2", &xtdc_t_6_2, &b_xtdc_t_6_2);
   fChain->SetBranchAddress("ytdc_t_6_2", &ytdc_t_6_2, &b_ytdc_t_6_2);
   fChain->SetBranchAddress("xtdc_l_6_3", &xtdc_l_6_3, &b_xtdc_l_6_3);
   fChain->SetBranchAddress("ytdc_l_6_3", &ytdc_l_6_3, &b_ytdc_l_6_3);
   fChain->SetBranchAddress("xtdc_t_6_3", &xtdc_t_6_3, &b_xtdc_t_6_3);
   fChain->SetBranchAddress("ytdc_t_6_3", &ytdc_t_6_3, &b_ytdc_t_6_3);
   fChain->SetBranchAddress("xtdc_l_6_4", &xtdc_l_6_4, &b_xtdc_l_6_4);
   fChain->SetBranchAddress("ytdc_l_6_4", &ytdc_l_6_4, &b_ytdc_l_6_4);
   fChain->SetBranchAddress("xtdc_t_6_4", &xtdc_t_6_4, &b_xtdc_t_6_4);
   fChain->SetBranchAddress("ytdc_t_6_4", &ytdc_t_6_4, &b_ytdc_t_6_4);
   fChain->SetBranchAddress("xtdc_l_6_5", &xtdc_l_6_5, &b_xtdc_l_6_5);
   fChain->SetBranchAddress("ytdc_l_6_5", &ytdc_l_6_5, &b_ytdc_l_6_5);
   fChain->SetBranchAddress("xtdc_t_6_5", &xtdc_t_6_5, &b_xtdc_t_6_5);
   fChain->SetBranchAddress("ytdc_t_6_5", &ytdc_t_6_5, &b_ytdc_t_6_5);
   fChain->SetBranchAddress("xtdc_l_6_6", &xtdc_l_6_6, &b_xtdc_l_6_6);
   fChain->SetBranchAddress("ytdc_l_6_6", &ytdc_l_6_6, &b_ytdc_l_6_6);
   fChain->SetBranchAddress("xtdc_t_6_6", &xtdc_t_6_6, &b_xtdc_t_6_6);
   fChain->SetBranchAddress("ytdc_t_6_6", &ytdc_t_6_6, &b_ytdc_t_6_6);
   fChain->SetBranchAddress("xtdc_l_6_7", &xtdc_l_6_7, &b_xtdc_l_6_7);
   fChain->SetBranchAddress("ytdc_l_6_7", &ytdc_l_6_7, &b_ytdc_l_6_7);
   fChain->SetBranchAddress("xtdc_t_6_7", &xtdc_t_6_7, &b_xtdc_t_6_7);
   fChain->SetBranchAddress("ytdc_t_6_7", &ytdc_t_6_7, &b_ytdc_t_6_7);
   fChain->SetBranchAddress("xtdc_l_7_0", &xtdc_l_7_0, &b_xtdc_l_7_0);
   fChain->SetBranchAddress("ytdc_l_7_0", &ytdc_l_7_0, &b_ytdc_l_7_0);
   fChain->SetBranchAddress("xtdc_t_7_0", &xtdc_t_7_0, &b_xtdc_t_7_0);
   fChain->SetBranchAddress("ytdc_t_7_0", &ytdc_t_7_0, &b_ytdc_t_7_0);
   fChain->SetBranchAddress("xtdc_l_7_1", &xtdc_l_7_1, &b_xtdc_l_7_1);
   fChain->SetBranchAddress("ytdc_l_7_1", &ytdc_l_7_1, &b_ytdc_l_7_1);
   fChain->SetBranchAddress("xtdc_t_7_1", &xtdc_t_7_1, &b_xtdc_t_7_1);
   fChain->SetBranchAddress("ytdc_t_7_1", &ytdc_t_7_1, &b_ytdc_t_7_1);
   fChain->SetBranchAddress("xtdc_l_7_2", &xtdc_l_7_2, &b_xtdc_l_7_2);
   fChain->SetBranchAddress("ytdc_l_7_2", &ytdc_l_7_2, &b_ytdc_l_7_2);
   fChain->SetBranchAddress("xtdc_t_7_2", &xtdc_t_7_2, &b_xtdc_t_7_2);
   fChain->SetBranchAddress("ytdc_t_7_2", &ytdc_t_7_2, &b_ytdc_t_7_2);
   fChain->SetBranchAddress("xtdc_l_7_3", &xtdc_l_7_3, &b_xtdc_l_7_3);
   fChain->SetBranchAddress("ytdc_l_7_3", &ytdc_l_7_3, &b_ytdc_l_7_3);
   fChain->SetBranchAddress("xtdc_t_7_3", &xtdc_t_7_3, &b_xtdc_t_7_3);
   fChain->SetBranchAddress("ytdc_t_7_3", &ytdc_t_7_3, &b_ytdc_t_7_3);
   fChain->SetBranchAddress("xtdc_l_7_4", &xtdc_l_7_4, &b_xtdc_l_7_4);
   fChain->SetBranchAddress("ytdc_l_7_4", &ytdc_l_7_4, &b_ytdc_l_7_4);
   fChain->SetBranchAddress("xtdc_t_7_4", &xtdc_t_7_4, &b_xtdc_t_7_4);
   fChain->SetBranchAddress("ytdc_t_7_4", &ytdc_t_7_4, &b_ytdc_t_7_4);
   fChain->SetBranchAddress("xtdc_l_7_5", &xtdc_l_7_5, &b_xtdc_l_7_5);
   fChain->SetBranchAddress("ytdc_l_7_5", &ytdc_l_7_5, &b_ytdc_l_7_5);
   fChain->SetBranchAddress("xtdc_t_7_5", &xtdc_t_7_5, &b_xtdc_t_7_5);
   fChain->SetBranchAddress("ytdc_t_7_5", &ytdc_t_7_5, &b_ytdc_t_7_5);
   fChain->SetBranchAddress("xtdc_l_7_6", &xtdc_l_7_6, &b_xtdc_l_7_6);
   fChain->SetBranchAddress("ytdc_l_7_6", &ytdc_l_7_6, &b_ytdc_l_7_6);
   fChain->SetBranchAddress("xtdc_t_7_6", &xtdc_t_7_6, &b_xtdc_t_7_6);
   fChain->SetBranchAddress("ytdc_t_7_6", &ytdc_t_7_6, &b_ytdc_t_7_6);
   fChain->SetBranchAddress("xtdc_l_7_7", &xtdc_l_7_7, &b_xtdc_l_7_7);
   fChain->SetBranchAddress("ytdc_l_7_7", &ytdc_l_7_7, &b_ytdc_l_7_7);
   fChain->SetBranchAddress("xtdc_t_7_7", &xtdc_t_7_7, &b_xtdc_t_7_7);
   fChain->SetBranchAddress("ytdc_t_7_7", &ytdc_t_7_7, &b_ytdc_t_7_7);
   fChain->SetBranchAddress("xtdc_l_8_0", &xtdc_l_8_0, &b_xtdc_l_8_0);
   fChain->SetBranchAddress("ytdc_l_8_0", &ytdc_l_8_0, &b_ytdc_l_8_0);
   fChain->SetBranchAddress("xtdc_t_8_0", &xtdc_t_8_0, &b_xtdc_t_8_0);
   fChain->SetBranchAddress("ytdc_t_8_0", &ytdc_t_8_0, &b_ytdc_t_8_0);
   fChain->SetBranchAddress("xtdc_l_8_1", &xtdc_l_8_1, &b_xtdc_l_8_1);
   fChain->SetBranchAddress("ytdc_l_8_1", &ytdc_l_8_1, &b_ytdc_l_8_1);
   fChain->SetBranchAddress("xtdc_t_8_1", &xtdc_t_8_1, &b_xtdc_t_8_1);
   fChain->SetBranchAddress("ytdc_t_8_1", &ytdc_t_8_1, &b_ytdc_t_8_1);
   fChain->SetBranchAddress("xtdc_l_8_2", &xtdc_l_8_2, &b_xtdc_l_8_2);
   fChain->SetBranchAddress("ytdc_l_8_2", &ytdc_l_8_2, &b_ytdc_l_8_2);
   fChain->SetBranchAddress("xtdc_t_8_2", &xtdc_t_8_2, &b_xtdc_t_8_2);
   fChain->SetBranchAddress("ytdc_t_8_2", &ytdc_t_8_2, &b_ytdc_t_8_2);
   fChain->SetBranchAddress("xtdc_l_8_3", &xtdc_l_8_3, &b_xtdc_l_8_3);
   fChain->SetBranchAddress("ytdc_l_8_3", &ytdc_l_8_3, &b_ytdc_l_8_3);
   fChain->SetBranchAddress("xtdc_t_8_3", &xtdc_t_8_3, &b_xtdc_t_8_3);
   fChain->SetBranchAddress("ytdc_t_8_3", &ytdc_t_8_3, &b_ytdc_t_8_3);
   fChain->SetBranchAddress("xtdc_l_8_4", &xtdc_l_8_4, &b_xtdc_l_8_4);
   fChain->SetBranchAddress("ytdc_l_8_4", &ytdc_l_8_4, &b_ytdc_l_8_4);
   fChain->SetBranchAddress("xtdc_t_8_4", &xtdc_t_8_4, &b_xtdc_t_8_4);
   fChain->SetBranchAddress("ytdc_t_8_4", &ytdc_t_8_4, &b_ytdc_t_8_4);
   fChain->SetBranchAddress("xtdc_l_8_5", &xtdc_l_8_5, &b_xtdc_l_8_5);
   fChain->SetBranchAddress("ytdc_l_8_5", &ytdc_l_8_5, &b_ytdc_l_8_5);
   fChain->SetBranchAddress("xtdc_t_8_5", &xtdc_t_8_5, &b_xtdc_t_8_5);
   fChain->SetBranchAddress("ytdc_t_8_5", &ytdc_t_8_5, &b_ytdc_t_8_5);
   fChain->SetBranchAddress("xtdc_l_8_6", &xtdc_l_8_6, &b_xtdc_l_8_6);
   fChain->SetBranchAddress("ytdc_l_8_6", &ytdc_l_8_6, &b_ytdc_l_8_6);
   fChain->SetBranchAddress("xtdc_t_8_6", &xtdc_t_8_6, &b_xtdc_t_8_6);
   fChain->SetBranchAddress("ytdc_t_8_6", &ytdc_t_8_6, &b_ytdc_t_8_6);
   fChain->SetBranchAddress("xtdc_l_8_7", &xtdc_l_8_7, &b_xtdc_l_8_7);
   fChain->SetBranchAddress("ytdc_l_8_7", &ytdc_l_8_7, &b_ytdc_l_8_7);
   fChain->SetBranchAddress("xtdc_t_8_7", &xtdc_t_8_7, &b_xtdc_t_8_7);
   fChain->SetBranchAddress("ytdc_t_8_7", &ytdc_t_8_7, &b_ytdc_t_8_7);
   fChain->SetBranchAddress("xtdc_l_9_0", &xtdc_l_9_0, &b_xtdc_l_9_0);
   fChain->SetBranchAddress("ytdc_l_9_0", &ytdc_l_9_0, &b_ytdc_l_9_0);
   fChain->SetBranchAddress("xtdc_t_9_0", &xtdc_t_9_0, &b_xtdc_t_9_0);
   fChain->SetBranchAddress("ytdc_t_9_0", &ytdc_t_9_0, &b_ytdc_t_9_0);
   fChain->SetBranchAddress("xtdc_l_9_1", &xtdc_l_9_1, &b_xtdc_l_9_1);
   fChain->SetBranchAddress("ytdc_l_9_1", &ytdc_l_9_1, &b_ytdc_l_9_1);
   fChain->SetBranchAddress("xtdc_t_9_1", &xtdc_t_9_1, &b_xtdc_t_9_1);
   fChain->SetBranchAddress("ytdc_t_9_1", &ytdc_t_9_1, &b_ytdc_t_9_1);
   fChain->SetBranchAddress("xtdc_l_9_2", &xtdc_l_9_2, &b_xtdc_l_9_2);
   fChain->SetBranchAddress("ytdc_l_9_2", &ytdc_l_9_2, &b_ytdc_l_9_2);
   fChain->SetBranchAddress("xtdc_t_9_2", &xtdc_t_9_2, &b_xtdc_t_9_2);
   fChain->SetBranchAddress("ytdc_t_9_2", &ytdc_t_9_2, &b_ytdc_t_9_2);
   fChain->SetBranchAddress("xtdc_l_9_3", &xtdc_l_9_3, &b_xtdc_l_9_3);
   fChain->SetBranchAddress("ytdc_l_9_3", &ytdc_l_9_3, &b_ytdc_l_9_3);
   fChain->SetBranchAddress("xtdc_t_9_3", &xtdc_t_9_3, &b_xtdc_t_9_3);
   fChain->SetBranchAddress("ytdc_t_9_3", &ytdc_t_9_3, &b_ytdc_t_9_3);
   fChain->SetBranchAddress("xtdc_l_9_4", &xtdc_l_9_4, &b_xtdc_l_9_4);
   fChain->SetBranchAddress("ytdc_l_9_4", &ytdc_l_9_4, &b_ytdc_l_9_4);
   fChain->SetBranchAddress("xtdc_t_9_4", &xtdc_t_9_4, &b_xtdc_t_9_4);
   fChain->SetBranchAddress("ytdc_t_9_4", &ytdc_t_9_4, &b_ytdc_t_9_4);
   fChain->SetBranchAddress("xtdc_l_9_5", &xtdc_l_9_5, &b_xtdc_l_9_5);
   fChain->SetBranchAddress("ytdc_l_9_5", &ytdc_l_9_5, &b_ytdc_l_9_5);
   fChain->SetBranchAddress("xtdc_t_9_5", &xtdc_t_9_5, &b_xtdc_t_9_5);
   fChain->SetBranchAddress("ytdc_t_9_5", &ytdc_t_9_5, &b_ytdc_t_9_5);
   fChain->SetBranchAddress("xtdc_l_9_6", &xtdc_l_9_6, &b_xtdc_l_9_6);
   fChain->SetBranchAddress("ytdc_l_9_6", &ytdc_l_9_6, &b_ytdc_l_9_6);
   fChain->SetBranchAddress("xtdc_t_9_6", &xtdc_t_9_6, &b_xtdc_t_9_6);
   fChain->SetBranchAddress("ytdc_t_9_6", &ytdc_t_9_6, &b_ytdc_t_9_6);
   fChain->SetBranchAddress("xtdc_l_9_7", &xtdc_l_9_7, &b_xtdc_l_9_7);
   fChain->SetBranchAddress("ytdc_l_9_7", &ytdc_l_9_7, &b_ytdc_l_9_7);
   fChain->SetBranchAddress("xtdc_t_9_7", &xtdc_t_9_7, &b_xtdc_t_9_7);
   fChain->SetBranchAddress("ytdc_t_9_7", &ytdc_t_9_7, &b_ytdc_t_9_7);
   fChain->SetBranchAddress("xtdc_l_10_0", &xtdc_l_10_0, &b_xtdc_l_10_0);
   fChain->SetBranchAddress("ytdc_l_10_0", &ytdc_l_10_0, &b_ytdc_l_10_0);
   fChain->SetBranchAddress("xtdc_t_10_0", &xtdc_t_10_0, &b_xtdc_t_10_0);
   fChain->SetBranchAddress("ytdc_t_10_0", &ytdc_t_10_0, &b_ytdc_t_10_0);
   fChain->SetBranchAddress("xtdc_l_10_1", &xtdc_l_10_1, &b_xtdc_l_10_1);
   fChain->SetBranchAddress("ytdc_l_10_1", &ytdc_l_10_1, &b_ytdc_l_10_1);
   fChain->SetBranchAddress("xtdc_t_10_1", &xtdc_t_10_1, &b_xtdc_t_10_1);
   fChain->SetBranchAddress("ytdc_t_10_1", &ytdc_t_10_1, &b_ytdc_t_10_1);
   fChain->SetBranchAddress("xtdc_l_10_2", &xtdc_l_10_2, &b_xtdc_l_10_2);
   fChain->SetBranchAddress("ytdc_l_10_2", &ytdc_l_10_2, &b_ytdc_l_10_2);
   fChain->SetBranchAddress("xtdc_t_10_2", &xtdc_t_10_2, &b_xtdc_t_10_2);
   fChain->SetBranchAddress("ytdc_t_10_2", &ytdc_t_10_2, &b_ytdc_t_10_2);
   fChain->SetBranchAddress("xtdc_l_10_3", &xtdc_l_10_3, &b_xtdc_l_10_3);
   fChain->SetBranchAddress("ytdc_l_10_3", &ytdc_l_10_3, &b_ytdc_l_10_3);
   fChain->SetBranchAddress("xtdc_t_10_3", &xtdc_t_10_3, &b_xtdc_t_10_3);
   fChain->SetBranchAddress("ytdc_t_10_3", &ytdc_t_10_3, &b_ytdc_t_10_3);
   fChain->SetBranchAddress("xtdc_l_10_4", &xtdc_l_10_4, &b_xtdc_l_10_4);
   fChain->SetBranchAddress("ytdc_l_10_4", &ytdc_l_10_4, &b_ytdc_l_10_4);
   fChain->SetBranchAddress("xtdc_t_10_4", &xtdc_t_10_4, &b_xtdc_t_10_4);
   fChain->SetBranchAddress("ytdc_t_10_4", &ytdc_t_10_4, &b_ytdc_t_10_4);
   fChain->SetBranchAddress("xtdc_l_10_5", &xtdc_l_10_5, &b_xtdc_l_10_5);
   fChain->SetBranchAddress("ytdc_l_10_5", &ytdc_l_10_5, &b_ytdc_l_10_5);
   fChain->SetBranchAddress("xtdc_t_10_5", &xtdc_t_10_5, &b_xtdc_t_10_5);
   fChain->SetBranchAddress("ytdc_t_10_5", &ytdc_t_10_5, &b_ytdc_t_10_5);
   fChain->SetBranchAddress("xtdc_l_10_6", &xtdc_l_10_6, &b_xtdc_l_10_6);
   fChain->SetBranchAddress("ytdc_l_10_6", &ytdc_l_10_6, &b_ytdc_l_10_6);
   fChain->SetBranchAddress("xtdc_t_10_6", &xtdc_t_10_6, &b_xtdc_t_10_6);
   fChain->SetBranchAddress("ytdc_t_10_6", &ytdc_t_10_6, &b_ytdc_t_10_6);
   fChain->SetBranchAddress("xtdc_l_10_7", &xtdc_l_10_7, &b_xtdc_l_10_7);
   fChain->SetBranchAddress("ytdc_l_10_7", &ytdc_l_10_7, &b_ytdc_l_10_7);
   fChain->SetBranchAddress("xtdc_t_10_7", &xtdc_t_10_7, &b_xtdc_t_10_7);
   fChain->SetBranchAddress("ytdc_t_10_7", &ytdc_t_10_7, &b_ytdc_t_10_7);
   fChain->SetBranchAddress("xtdc_l_11_0", &xtdc_l_11_0, &b_xtdc_l_11_0);
   fChain->SetBranchAddress("ytdc_l_11_0", &ytdc_l_11_0, &b_ytdc_l_11_0);
   fChain->SetBranchAddress("xtdc_t_11_0", &xtdc_t_11_0, &b_xtdc_t_11_0);
   fChain->SetBranchAddress("ytdc_t_11_0", &ytdc_t_11_0, &b_ytdc_t_11_0);
   fChain->SetBranchAddress("xtdc_l_11_1", &xtdc_l_11_1, &b_xtdc_l_11_1);
   fChain->SetBranchAddress("ytdc_l_11_1", &ytdc_l_11_1, &b_ytdc_l_11_1);
   fChain->SetBranchAddress("xtdc_t_11_1", &xtdc_t_11_1, &b_xtdc_t_11_1);
   fChain->SetBranchAddress("ytdc_t_11_1", &ytdc_t_11_1, &b_ytdc_t_11_1);
   fChain->SetBranchAddress("xtdc_l_11_2", &xtdc_l_11_2, &b_xtdc_l_11_2);
   fChain->SetBranchAddress("ytdc_l_11_2", &ytdc_l_11_2, &b_ytdc_l_11_2);
   fChain->SetBranchAddress("xtdc_t_11_2", &xtdc_t_11_2, &b_xtdc_t_11_2);
   fChain->SetBranchAddress("ytdc_t_11_2", &ytdc_t_11_2, &b_ytdc_t_11_2);
   fChain->SetBranchAddress("xtdc_l_11_3", &xtdc_l_11_3, &b_xtdc_l_11_3);
   fChain->SetBranchAddress("ytdc_l_11_3", &ytdc_l_11_3, &b_ytdc_l_11_3);
   fChain->SetBranchAddress("xtdc_t_11_3", &xtdc_t_11_3, &b_xtdc_t_11_3);
   fChain->SetBranchAddress("ytdc_t_11_3", &ytdc_t_11_3, &b_ytdc_t_11_3);
   fChain->SetBranchAddress("xtdc_l_11_4", &xtdc_l_11_4, &b_xtdc_l_11_4);
   fChain->SetBranchAddress("ytdc_l_11_4", &ytdc_l_11_4, &b_ytdc_l_11_4);
   fChain->SetBranchAddress("xtdc_t_11_4", &xtdc_t_11_4, &b_xtdc_t_11_4);
   fChain->SetBranchAddress("ytdc_t_11_4", &ytdc_t_11_4, &b_ytdc_t_11_4);
   fChain->SetBranchAddress("xtdc_l_11_5", &xtdc_l_11_5, &b_xtdc_l_11_5);
   fChain->SetBranchAddress("ytdc_l_11_5", &ytdc_l_11_5, &b_ytdc_l_11_5);
   fChain->SetBranchAddress("xtdc_t_11_5", &xtdc_t_11_5, &b_xtdc_t_11_5);
   fChain->SetBranchAddress("ytdc_t_11_5", &ytdc_t_11_5, &b_ytdc_t_11_5);
   fChain->SetBranchAddress("xtdc_l_11_6", &xtdc_l_11_6, &b_xtdc_l_11_6);
   fChain->SetBranchAddress("ytdc_l_11_6", &ytdc_l_11_6, &b_ytdc_l_11_6);
   fChain->SetBranchAddress("xtdc_t_11_6", &xtdc_t_11_6, &b_xtdc_t_11_6);
   fChain->SetBranchAddress("ytdc_t_11_6", &ytdc_t_11_6, &b_ytdc_t_11_6);
   fChain->SetBranchAddress("xtdc_l_11_7", &xtdc_l_11_7, &b_xtdc_l_11_7);
   fChain->SetBranchAddress("ytdc_l_11_7", &ytdc_l_11_7, &b_ytdc_l_11_7);
   fChain->SetBranchAddress("xtdc_t_11_7", &xtdc_t_11_7, &b_xtdc_t_11_7);
   fChain->SetBranchAddress("ytdc_t_11_7", &ytdc_t_11_7, &b_ytdc_t_11_7);
   Notify();
}

Bool_t RPCEve::Notify()
{
   // The Notify() function is called when a new file is opened. This
   // can be either for a new TTree in a TChain or when when a new TTree
   // is started when using PROOF. It is normally not necessary to make changes
   // to the generated code, but the routine can be extended by the
   // user if needed. The return value is currently not used.

   return kTRUE;
}

void RPCEve::Show(Long64_t entry)
{
// Print contents of entry.
// If entry is not specified, print current entry
   if (!fChain) return;
   fChain->Show(entry);
}
Int_t RPCEve::Cut(Long64_t entry)
{
// This function may be called from Loop.
// returns  1 if entry is accepted.
// returns -1 otherwise.
   return 1;
}
#endif // #ifdef RPCEve_cxx
